// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"network-sec-micro/internal/warrior"
)

// Injectors from wire.go:

func InitializeApp() (*warrior.Service, *warrior.Handler, error) {
	service := warrior.NewService()
	handler := warrior.NewHandler(service)
	return service, handler, nil
}