// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/arenaspell/arenaspell.proto

package arenaspell

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArenaSpellService_CastSpell_FullMethodName = "/arenaspell.ArenaSpellService/CastSpell"
)

// ArenaSpellServiceClient is the client API for ArenaSpellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArenaSpell Service (called by Arena or API layer to cast a 1v1 spell)
type ArenaSpellServiceClient interface {
	CastSpell(ctx context.Context, in *CastArenaSpellRequest, opts ...grpc.CallOption) (*CastArenaSpellResponse, error)
}

type arenaSpellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArenaSpellServiceClient(cc grpc.ClientConnInterface) ArenaSpellServiceClient {
	return &arenaSpellServiceClient{cc}
}

func (c *arenaSpellServiceClient) CastSpell(ctx context.Context, in *CastArenaSpellRequest, opts ...grpc.CallOption) (*CastArenaSpellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CastArenaSpellResponse)
	err := c.cc.Invoke(ctx, ArenaSpellService_CastSpell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaSpellServiceServer is the server API for ArenaSpellService service.
// All implementations must embed UnimplementedArenaSpellServiceServer
// for forward compatibility.
//
// ArenaSpell Service (called by Arena or API layer to cast a 1v1 spell)
type ArenaSpellServiceServer interface {
	CastSpell(context.Context, *CastArenaSpellRequest) (*CastArenaSpellResponse, error)
	mustEmbedUnimplementedArenaSpellServiceServer()
}

// UnimplementedArenaSpellServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArenaSpellServiceServer struct{}

func (UnimplementedArenaSpellServiceServer) CastSpell(context.Context, *CastArenaSpellRequest) (*CastArenaSpellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastSpell not implemented")
}
func (UnimplementedArenaSpellServiceServer) mustEmbedUnimplementedArenaSpellServiceServer() {}
func (UnimplementedArenaSpellServiceServer) testEmbeddedByValue()                           {}

// UnsafeArenaSpellServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArenaSpellServiceServer will
// result in compilation errors.
type UnsafeArenaSpellServiceServer interface {
	mustEmbedUnimplementedArenaSpellServiceServer()
}

func RegisterArenaSpellServiceServer(s grpc.ServiceRegistrar, srv ArenaSpellServiceServer) {
	// If the following call pancis, it indicates UnimplementedArenaSpellServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArenaSpellService_ServiceDesc, srv)
}

func _ArenaSpellService_CastSpell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastArenaSpellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaSpellServiceServer).CastSpell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaSpellService_CastSpell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaSpellServiceServer).CastSpell(ctx, req.(*CastArenaSpellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArenaSpellService_ServiceDesc is the grpc.ServiceDesc for ArenaSpellService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArenaSpellService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arenaspell.ArenaSpellService",
	HandlerType: (*ArenaSpellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CastSpell",
			Handler:    _ArenaSpellService_CastSpell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/arenaspell/arenaspell.proto",
}
