// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/arenaspell/arenaspell.proto

package arenaspell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastArenaSpellRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MatchId        string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	SpellType      string                 `protobuf:"bytes,2,opt,name=spell_type,json=spellType,proto3" json:"spell_type,omitempty"` // call_of_the_light_king | resistance | rebirth | destroy_the_light
	CasterUserId   uint32                 `protobuf:"varint,3,opt,name=caster_user_id,json=casterUserId,proto3" json:"caster_user_id,omitempty"`
	CasterUsername string                 `protobuf:"bytes,4,opt,name=caster_username,json=casterUsername,proto3" json:"caster_username,omitempty"`
	CasterRole     string                 `protobuf:"bytes,5,opt,name=caster_role,json=casterRole,proto3" json:"caster_role,omitempty"` // light_king | dark_king
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CastArenaSpellRequest) Reset() {
	*x = CastArenaSpellRequest{}
	mi := &file_api_proto_arenaspell_arenaspell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastArenaSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastArenaSpellRequest) ProtoMessage() {}

func (x *CastArenaSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arenaspell_arenaspell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastArenaSpellRequest.ProtoReflect.Descriptor instead.
func (*CastArenaSpellRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_arenaspell_arenaspell_proto_rawDescGZIP(), []int{0}
}

func (x *CastArenaSpellRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *CastArenaSpellRequest) GetSpellType() string {
	if x != nil {
		return x.SpellType
	}
	return ""
}

func (x *CastArenaSpellRequest) GetCasterUserId() uint32 {
	if x != nil {
		return x.CasterUserId
	}
	return 0
}

func (x *CastArenaSpellRequest) GetCasterUsername() string {
	if x != nil {
		return x.CasterUsername
	}
	return ""
}

func (x *CastArenaSpellRequest) GetCasterRole() string {
	if x != nil {
		return x.CasterRole
	}
	return ""
}

type CastArenaSpellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AffectedCount int32                  `protobuf:"varint,3,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastArenaSpellResponse) Reset() {
	*x = CastArenaSpellResponse{}
	mi := &file_api_proto_arenaspell_arenaspell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastArenaSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastArenaSpellResponse) ProtoMessage() {}

func (x *CastArenaSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arenaspell_arenaspell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastArenaSpellResponse.ProtoReflect.Descriptor instead.
func (*CastArenaSpellResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_arenaspell_arenaspell_proto_rawDescGZIP(), []int{1}
}

func (x *CastArenaSpellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CastArenaSpellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CastArenaSpellResponse) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

var File_api_proto_arenaspell_arenaspell_proto protoreflect.FileDescriptor

const file_api_proto_arenaspell_arenaspell_proto_rawDesc = "" +
	"\n" +
	"%api/proto/arenaspell/arenaspell.proto\x12\n" +
	"arenaspell\"\xc1\x01\n" +
	"\x15CastArenaSpellRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"spell_type\x18\x02 \x01(\tR\tspellType\x12$\n" +
	"\x0ecaster_user_id\x18\x03 \x01(\rR\fcasterUserId\x12'\n" +
	"\x0fcaster_username\x18\x04 \x01(\tR\x0ecasterUsername\x12\x1f\n" +
	"\vcaster_role\x18\x05 \x01(\tR\n" +
	"casterRole\"s\n" +
	"\x16CastArenaSpellResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaffected_count\x18\x03 \x01(\x05R\raffectedCount2g\n" +
	"\x11ArenaSpellService\x12R\n" +
	"\tCastSpell\x12!.arenaspell.CastArenaSpellRequest\x1a\".arenaspell.CastArenaSpellResponseB(Z&network-sec-micro/api/proto/arenaspellb\x06proto3"

var (
	file_api_proto_arenaspell_arenaspell_proto_rawDescOnce sync.Once
	file_api_proto_arenaspell_arenaspell_proto_rawDescData []byte
)

func file_api_proto_arenaspell_arenaspell_proto_rawDescGZIP() []byte {
	file_api_proto_arenaspell_arenaspell_proto_rawDescOnce.Do(func() {
		file_api_proto_arenaspell_arenaspell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_arenaspell_arenaspell_proto_rawDesc), len(file_api_proto_arenaspell_arenaspell_proto_rawDesc)))
	})
	return file_api_proto_arenaspell_arenaspell_proto_rawDescData
}

var file_api_proto_arenaspell_arenaspell_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_arenaspell_arenaspell_proto_goTypes = []any{
	(*CastArenaSpellRequest)(nil),  // 0: arenaspell.CastArenaSpellRequest
	(*CastArenaSpellResponse)(nil), // 1: arenaspell.CastArenaSpellResponse
}
var file_api_proto_arenaspell_arenaspell_proto_depIdxs = []int32{
	0, // 0: arenaspell.ArenaSpellService.CastSpell:input_type -> arenaspell.CastArenaSpellRequest
	1, // 1: arenaspell.ArenaSpellService.CastSpell:output_type -> arenaspell.CastArenaSpellResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_arenaspell_arenaspell_proto_init() }
func file_api_proto_arenaspell_arenaspell_proto_init() {
	if File_api_proto_arenaspell_arenaspell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_arenaspell_arenaspell_proto_rawDesc), len(file_api_proto_arenaspell_arenaspell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_arenaspell_arenaspell_proto_goTypes,
		DependencyIndexes: file_api_proto_arenaspell_arenaspell_proto_depIdxs,
		MessageInfos:      file_api_proto_arenaspell_arenaspell_proto_msgTypes,
	}.Build()
	File_api_proto_arenaspell_arenaspell_proto = out.File
	file_api_proto_arenaspell_arenaspell_proto_goTypes = nil
	file_api_proto_arenaspell_arenaspell_proto_depIdxs = nil
}
