// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/battle/battle.proto

package battle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get battle by ID
type GetBattleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleByIDRequest) Reset() {
	*x = GetBattleByIDRequest{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleByIDRequest) ProtoMessage() {}

func (x *GetBattleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBattleByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{0}
}

func (x *GetBattleByIDRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

// Response with battle
type GetBattleByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Battle        *Battle                `protobuf:"bytes,1,opt,name=battle,proto3" json:"battle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleByIDResponse) Reset() {
	*x = GetBattleByIDResponse{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleByIDResponse) ProtoMessage() {}

func (x *GetBattleByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleByIDResponse.ProtoReflect.Descriptor instead.
func (*GetBattleByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{1}
}

func (x *GetBattleByIDResponse) GetBattle() *Battle {
	if x != nil {
		return x.Battle
	}
	return nil
}

// Request to get active battles
type GetActiveBattlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          string                 `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"` // "light" or "dark" (optional filter)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveBattlesRequest) Reset() {
	*x = GetActiveBattlesRequest{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveBattlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveBattlesRequest) ProtoMessage() {}

func (x *GetActiveBattlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveBattlesRequest.ProtoReflect.Descriptor instead.
func (*GetActiveBattlesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{2}
}

func (x *GetActiveBattlesRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

// Response with active battles
type GetActiveBattlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Battles       []*Battle              `protobuf:"bytes,1,rep,name=battles,proto3" json:"battles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveBattlesResponse) Reset() {
	*x = GetActiveBattlesResponse{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveBattlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveBattlesResponse) ProtoMessage() {}

func (x *GetActiveBattlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveBattlesResponse.ProtoReflect.Descriptor instead.
func (*GetActiveBattlesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{3}
}

func (x *GetActiveBattlesResponse) GetBattles() []*Battle {
	if x != nil {
		return x.Battles
	}
	return nil
}

// Request to get battle participants
type GetBattleParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"` // "light" or "dark" (optional filter)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleParticipantsRequest) Reset() {
	*x = GetBattleParticipantsRequest{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleParticipantsRequest) ProtoMessage() {}

func (x *GetBattleParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetBattleParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{4}
}

func (x *GetBattleParticipantsRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *GetBattleParticipantsRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

// Response with participants
type GetBattleParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*BattleParticipant   `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleParticipantsResponse) Reset() {
	*x = GetBattleParticipantsResponse{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleParticipantsResponse) ProtoMessage() {}

func (x *GetBattleParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetBattleParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{5}
}

func (x *GetBattleParticipantsResponse) GetParticipants() []*BattleParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

// Request to update participant stats
type UpdateParticipantStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Hp            int32                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	AttackPower   int32                  `protobuf:"varint,5,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Defense       int32                  `protobuf:"varint,6,opt,name=defense,proto3" json:"defense,omitempty"`
	IsAlive       bool                   `protobuf:"varint,7,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParticipantStatsRequest) Reset() {
	*x = UpdateParticipantStatsRequest{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParticipantStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParticipantStatsRequest) ProtoMessage() {}

func (x *UpdateParticipantStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParticipantStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateParticipantStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateParticipantStatsRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *UpdateParticipantStatsRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *UpdateParticipantStatsRequest) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *UpdateParticipantStatsRequest) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *UpdateParticipantStatsRequest) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *UpdateParticipantStatsRequest) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *UpdateParticipantStatsRequest) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

// Response after updating stats
type UpdateParticipantStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParticipantStatsResponse) Reset() {
	*x = UpdateParticipantStatsResponse{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParticipantStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParticipantStatsResponse) ProtoMessage() {}

func (x *UpdateParticipantStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParticipantStatsResponse.ProtoReflect.Descriptor instead.
func (*UpdateParticipantStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateParticipantStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateParticipantStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to cast spell
type CastSpellRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BattleId            string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	SpellType           string                 `protobuf:"bytes,2,opt,name=spell_type,json=spellType,proto3" json:"spell_type,omitempty"`
	CasterUsername      string                 `protobuf:"bytes,3,opt,name=caster_username,json=casterUsername,proto3" json:"caster_username,omitempty"`
	CasterUserId        string                 `protobuf:"bytes,4,opt,name=caster_user_id,json=casterUserId,proto3" json:"caster_user_id,omitempty"`
	CasterRole          string                 `protobuf:"bytes,5,opt,name=caster_role,json=casterRole,proto3" json:"caster_role,omitempty"`
	TargetDragonId      string                 `protobuf:"bytes,6,opt,name=target_dragon_id,json=targetDragonId,proto3" json:"target_dragon_id,omitempty"`
	TargetDarkEmperorId string                 `protobuf:"bytes,7,opt,name=target_dark_emperor_id,json=targetDarkEmperorId,proto3" json:"target_dark_emperor_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CastSpellRequest) Reset() {
	*x = CastSpellRequest{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellRequest) ProtoMessage() {}

func (x *CastSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellRequest.ProtoReflect.Descriptor instead.
func (*CastSpellRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{8}
}

func (x *CastSpellRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CastSpellRequest) GetSpellType() string {
	if x != nil {
		return x.SpellType
	}
	return ""
}

func (x *CastSpellRequest) GetCasterUsername() string {
	if x != nil {
		return x.CasterUsername
	}
	return ""
}

func (x *CastSpellRequest) GetCasterUserId() string {
	if x != nil {
		return x.CasterUserId
	}
	return ""
}

func (x *CastSpellRequest) GetCasterRole() string {
	if x != nil {
		return x.CasterRole
	}
	return ""
}

func (x *CastSpellRequest) GetTargetDragonId() string {
	if x != nil {
		return x.TargetDragonId
	}
	return ""
}

func (x *CastSpellRequest) GetTargetDarkEmperorId() string {
	if x != nil {
		return x.TargetDarkEmperorId
	}
	return ""
}

// Response after casting spell
type CastSpellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastSpellResponse) Reset() {
	*x = CastSpellResponse{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellResponse) ProtoMessage() {}

func (x *CastSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellResponse.ProtoReflect.Descriptor instead.
func (*CastSpellResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{9}
}

func (x *CastSpellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CastSpellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Battle model
type Battle struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BattleType              string                 `protobuf:"bytes,2,opt,name=battle_type,json=battleType,proto3" json:"battle_type,omitempty"`
	LightSideName           string                 `protobuf:"bytes,3,opt,name=light_side_name,json=lightSideName,proto3" json:"light_side_name,omitempty"`
	DarkSideName            string                 `protobuf:"bytes,4,opt,name=dark_side_name,json=darkSideName,proto3" json:"dark_side_name,omitempty"`
	CurrentTurn             int32                  `protobuf:"varint,5,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`
	CurrentParticipantIndex int32                  `protobuf:"varint,6,opt,name=current_participant_index,json=currentParticipantIndex,proto3" json:"current_participant_index,omitempty"`
	MaxTurns                int32                  `protobuf:"varint,7,opt,name=max_turns,json=maxTurns,proto3" json:"max_turns,omitempty"`
	Status                  string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Result                  string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	WinnerSide              string                 `protobuf:"bytes,10,opt,name=winner_side,json=winnerSide,proto3" json:"winner_side,omitempty"`
	CreatedBy               string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	StartedAt               *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Battle) Reset() {
	*x = Battle{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Battle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Battle) ProtoMessage() {}

func (x *Battle) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Battle.ProtoReflect.Descriptor instead.
func (*Battle) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{10}
}

func (x *Battle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Battle) GetBattleType() string {
	if x != nil {
		return x.BattleType
	}
	return ""
}

func (x *Battle) GetLightSideName() string {
	if x != nil {
		return x.LightSideName
	}
	return ""
}

func (x *Battle) GetDarkSideName() string {
	if x != nil {
		return x.DarkSideName
	}
	return ""
}

func (x *Battle) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *Battle) GetCurrentParticipantIndex() int32 {
	if x != nil {
		return x.CurrentParticipantIndex
	}
	return 0
}

func (x *Battle) GetMaxTurns() int32 {
	if x != nil {
		return x.MaxTurns
	}
	return 0
}

func (x *Battle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Battle) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Battle) GetWinnerSide() string {
	if x != nil {
		return x.WinnerSide
	}
	return ""
}

func (x *Battle) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Battle) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Battle) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Battle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Battle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// BattleParticipant model
type BattleParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BattleId      string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,3,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Side          string                 `protobuf:"bytes,6,opt,name=side,proto3" json:"side,omitempty"`
	Hp            int32                  `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,8,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	AttackPower   int32                  `protobuf:"varint,9,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Defense       int32                  `protobuf:"varint,10,opt,name=defense,proto3" json:"defense,omitempty"`
	IsAlive       bool                   `protobuf:"varint,11,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	IsDefeated    bool                   `protobuf:"varint,12,opt,name=is_defeated,json=isDefeated,proto3" json:"is_defeated,omitempty"`
	DefeatedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=defeated_at,json=defeatedAt,proto3" json:"defeated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleParticipant) Reset() {
	*x = BattleParticipant{}
	mi := &file_api_proto_battle_battle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleParticipant) ProtoMessage() {}

func (x *BattleParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battle_battle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleParticipant.ProtoReflect.Descriptor instead.
func (*BattleParticipant) Descriptor() ([]byte, []int) {
	return file_api_proto_battle_battle_proto_rawDescGZIP(), []int{11}
}

func (x *BattleParticipant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BattleParticipant) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleParticipant) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *BattleParticipant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BattleParticipant) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BattleParticipant) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *BattleParticipant) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *BattleParticipant) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *BattleParticipant) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *BattleParticipant) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *BattleParticipant) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *BattleParticipant) GetIsDefeated() bool {
	if x != nil {
		return x.IsDefeated
	}
	return false
}

func (x *BattleParticipant) GetDefeatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DefeatedAt
	}
	return nil
}

func (x *BattleParticipant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BattleParticipant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_proto_battle_battle_proto protoreflect.FileDescriptor

const file_api_proto_battle_battle_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/battle/battle.proto\x12\x06battle\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\x14GetBattleByIDRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"?\n" +
	"\x15GetBattleByIDResponse\x12&\n" +
	"\x06battle\x18\x01 \x01(\v2\x0e.battle.BattleR\x06battle\"-\n" +
	"\x17GetActiveBattlesRequest\x12\x12\n" +
	"\x04side\x18\x01 \x01(\tR\x04side\"D\n" +
	"\x18GetActiveBattlesResponse\x12(\n" +
	"\abattles\x18\x01 \x03(\v2\x0e.battle.BattleR\abattles\"O\n" +
	"\x1cGetBattleParticipantsRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\"^\n" +
	"\x1dGetBattleParticipantsResponse\x12=\n" +
	"\fparticipants\x18\x01 \x03(\v2\x19.battle.BattleParticipantR\fparticipants\"\xe2\x01\n" +
	"\x1dUpdateParticipantStatsRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12!\n" +
	"\fattack_power\x18\x05 \x01(\x05R\vattackPower\x12\x18\n" +
	"\adefense\x18\x06 \x01(\x05R\adefense\x12\x19\n" +
	"\bis_alive\x18\a \x01(\bR\aisAlive\"T\n" +
	"\x1eUpdateParticipantStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9d\x02\n" +
	"\x10CastSpellRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x1d\n" +
	"\n" +
	"spell_type\x18\x02 \x01(\tR\tspellType\x12'\n" +
	"\x0fcaster_username\x18\x03 \x01(\tR\x0ecasterUsername\x12$\n" +
	"\x0ecaster_user_id\x18\x04 \x01(\tR\fcasterUserId\x12\x1f\n" +
	"\vcaster_role\x18\x05 \x01(\tR\n" +
	"casterRole\x12(\n" +
	"\x10target_dragon_id\x18\x06 \x01(\tR\x0etargetDragonId\x123\n" +
	"\x16target_dark_emperor_id\x18\a \x01(\tR\x13targetDarkEmperorId\"G\n" +
	"\x11CastSpellResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe3\x04\n" +
	"\x06Battle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vbattle_type\x18\x02 \x01(\tR\n" +
	"battleType\x12&\n" +
	"\x0flight_side_name\x18\x03 \x01(\tR\rlightSideName\x12$\n" +
	"\x0edark_side_name\x18\x04 \x01(\tR\fdarkSideName\x12!\n" +
	"\fcurrent_turn\x18\x05 \x01(\x05R\vcurrentTurn\x12:\n" +
	"\x19current_participant_index\x18\x06 \x01(\x05R\x17currentParticipantIndex\x12\x1b\n" +
	"\tmax_turns\x18\a \x01(\x05R\bmaxTurns\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x1f\n" +
	"\vwinner_side\x18\n" +
	" \x01(\tR\n" +
	"winnerSide\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf6\x03\n" +
	"\x11BattleParticipant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\x12%\n" +
	"\x0eparticipant_id\x18\x03 \x01(\tR\rparticipantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04side\x18\x06 \x01(\tR\x04side\x12\x0e\n" +
	"\x02hp\x18\a \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\b \x01(\x05R\x05maxHp\x12!\n" +
	"\fattack_power\x18\t \x01(\x05R\vattackPower\x12\x18\n" +
	"\adefense\x18\n" +
	" \x01(\x05R\adefense\x12\x19\n" +
	"\bis_alive\x18\v \x01(\bR\aisAlive\x12\x1f\n" +
	"\vis_defeated\x18\f \x01(\bR\n" +
	"isDefeated\x12;\n" +
	"\vdefeated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"defeatedAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xc5\x03\n" +
	"\rBattleService\x12L\n" +
	"\rGetBattleByID\x12\x1c.battle.GetBattleByIDRequest\x1a\x1d.battle.GetBattleByIDResponse\x12U\n" +
	"\x10GetActiveBattles\x12\x1f.battle.GetActiveBattlesRequest\x1a .battle.GetActiveBattlesResponse\x12d\n" +
	"\x15GetBattleParticipants\x12$.battle.GetBattleParticipantsRequest\x1a%.battle.GetBattleParticipantsResponse\x12g\n" +
	"\x16UpdateParticipantStats\x12%.battle.UpdateParticipantStatsRequest\x1a&.battle.UpdateParticipantStatsResponse\x12@\n" +
	"\tCastSpell\x12\x18.battle.CastSpellRequest\x1a\x19.battle.CastSpellResponseB$Z\"network-sec-micro/api/proto/battleb\x06proto3"

var (
	file_api_proto_battle_battle_proto_rawDescOnce sync.Once
	file_api_proto_battle_battle_proto_rawDescData []byte
)

func file_api_proto_battle_battle_proto_rawDescGZIP() []byte {
	file_api_proto_battle_battle_proto_rawDescOnce.Do(func() {
		file_api_proto_battle_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_battle_battle_proto_rawDesc), len(file_api_proto_battle_battle_proto_rawDesc)))
	})
	return file_api_proto_battle_battle_proto_rawDescData
}

var file_api_proto_battle_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_battle_battle_proto_goTypes = []any{
	(*GetBattleByIDRequest)(nil),           // 0: battle.GetBattleByIDRequest
	(*GetBattleByIDResponse)(nil),          // 1: battle.GetBattleByIDResponse
	(*GetActiveBattlesRequest)(nil),        // 2: battle.GetActiveBattlesRequest
	(*GetActiveBattlesResponse)(nil),       // 3: battle.GetActiveBattlesResponse
	(*GetBattleParticipantsRequest)(nil),   // 4: battle.GetBattleParticipantsRequest
	(*GetBattleParticipantsResponse)(nil),  // 5: battle.GetBattleParticipantsResponse
	(*UpdateParticipantStatsRequest)(nil),  // 6: battle.UpdateParticipantStatsRequest
	(*UpdateParticipantStatsResponse)(nil), // 7: battle.UpdateParticipantStatsResponse
	(*CastSpellRequest)(nil),               // 8: battle.CastSpellRequest
	(*CastSpellResponse)(nil),              // 9: battle.CastSpellResponse
	(*Battle)(nil),                         // 10: battle.Battle
	(*BattleParticipant)(nil),              // 11: battle.BattleParticipant
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
}
var file_api_proto_battle_battle_proto_depIdxs = []int32{
	10, // 0: battle.GetBattleByIDResponse.battle:type_name -> battle.Battle
	10, // 1: battle.GetActiveBattlesResponse.battles:type_name -> battle.Battle
	11, // 2: battle.GetBattleParticipantsResponse.participants:type_name -> battle.BattleParticipant
	12, // 3: battle.Battle.started_at:type_name -> google.protobuf.Timestamp
	12, // 4: battle.Battle.completed_at:type_name -> google.protobuf.Timestamp
	12, // 5: battle.Battle.created_at:type_name -> google.protobuf.Timestamp
	12, // 6: battle.Battle.updated_at:type_name -> google.protobuf.Timestamp
	12, // 7: battle.BattleParticipant.defeated_at:type_name -> google.protobuf.Timestamp
	12, // 8: battle.BattleParticipant.created_at:type_name -> google.protobuf.Timestamp
	12, // 9: battle.BattleParticipant.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: battle.BattleService.GetBattleByID:input_type -> battle.GetBattleByIDRequest
	2,  // 11: battle.BattleService.GetActiveBattles:input_type -> battle.GetActiveBattlesRequest
	4,  // 12: battle.BattleService.GetBattleParticipants:input_type -> battle.GetBattleParticipantsRequest
	6,  // 13: battle.BattleService.UpdateParticipantStats:input_type -> battle.UpdateParticipantStatsRequest
	8,  // 14: battle.BattleService.CastSpell:input_type -> battle.CastSpellRequest
	1,  // 15: battle.BattleService.GetBattleByID:output_type -> battle.GetBattleByIDResponse
	3,  // 16: battle.BattleService.GetActiveBattles:output_type -> battle.GetActiveBattlesResponse
	5,  // 17: battle.BattleService.GetBattleParticipants:output_type -> battle.GetBattleParticipantsResponse
	7,  // 18: battle.BattleService.UpdateParticipantStats:output_type -> battle.UpdateParticipantStatsResponse
	9,  // 19: battle.BattleService.CastSpell:output_type -> battle.CastSpellResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_battle_battle_proto_init() }
func file_api_proto_battle_battle_proto_init() {
	if File_api_proto_battle_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_battle_battle_proto_rawDesc), len(file_api_proto_battle_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_battle_battle_proto_goTypes,
		DependencyIndexes: file_api_proto_battle_battle_proto_depIdxs,
		MessageInfos:      file_api_proto_battle_battle_proto_msgTypes,
	}.Build()
	File_api_proto_battle_battle_proto = out.File
	file_api_proto_battle_battle_proto_goTypes = nil
	file_api_proto_battle_battle_proto_depIdxs = nil
}
