// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/battle/battle.proto

package battle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleService_GetBattleByID_FullMethodName          = "/battle.BattleService/GetBattleByID"
	BattleService_GetActiveBattles_FullMethodName       = "/battle.BattleService/GetActiveBattles"
	BattleService_GetBattleParticipants_FullMethodName  = "/battle.BattleService/GetBattleParticipants"
	BattleService_UpdateParticipantStats_FullMethodName = "/battle.BattleService/UpdateParticipantStats"
	BattleService_CastSpell_FullMethodName              = "/battle.BattleService/CastSpell"
)

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Battle Service (gRPC methods for service-to-service communication)
type BattleServiceClient interface {
	// Get battle details by ID
	GetBattleByID(ctx context.Context, in *GetBattleByIDRequest, opts ...grpc.CallOption) (*GetBattleByIDResponse, error)
	// Get active battles
	GetActiveBattles(ctx context.Context, in *GetActiveBattlesRequest, opts ...grpc.CallOption) (*GetActiveBattlesResponse, error)
	// Get battle participants
	GetBattleParticipants(ctx context.Context, in *GetBattleParticipantsRequest, opts ...grpc.CallOption) (*GetBattleParticipantsResponse, error)
	// Update participant stats
	UpdateParticipantStats(ctx context.Context, in *UpdateParticipantStatsRequest, opts ...grpc.CallOption) (*UpdateParticipantStatsResponse, error)
	// Cast spell (called by other services if needed)
	CastSpell(ctx context.Context, in *CastSpellRequest, opts ...grpc.CallOption) (*CastSpellResponse, error)
}

type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) GetBattleByID(ctx context.Context, in *GetBattleByIDRequest, opts ...grpc.CallOption) (*GetBattleByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBattleByIDResponse)
	err := c.cc.Invoke(ctx, BattleService_GetBattleByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) GetActiveBattles(ctx context.Context, in *GetActiveBattlesRequest, opts ...grpc.CallOption) (*GetActiveBattlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveBattlesResponse)
	err := c.cc.Invoke(ctx, BattleService_GetActiveBattles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) GetBattleParticipants(ctx context.Context, in *GetBattleParticipantsRequest, opts ...grpc.CallOption) (*GetBattleParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBattleParticipantsResponse)
	err := c.cc.Invoke(ctx, BattleService_GetBattleParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) UpdateParticipantStats(ctx context.Context, in *UpdateParticipantStatsRequest, opts ...grpc.CallOption) (*UpdateParticipantStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateParticipantStatsResponse)
	err := c.cc.Invoke(ctx, BattleService_UpdateParticipantStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) CastSpell(ctx context.Context, in *CastSpellRequest, opts ...grpc.CallOption) (*CastSpellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CastSpellResponse)
	err := c.cc.Invoke(ctx, BattleService_CastSpell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleServiceServer is the server API for BattleService service.
// All implementations must embed UnimplementedBattleServiceServer
// for forward compatibility.
//
// Battle Service (gRPC methods for service-to-service communication)
type BattleServiceServer interface {
	// Get battle details by ID
	GetBattleByID(context.Context, *GetBattleByIDRequest) (*GetBattleByIDResponse, error)
	// Get active battles
	GetActiveBattles(context.Context, *GetActiveBattlesRequest) (*GetActiveBattlesResponse, error)
	// Get battle participants
	GetBattleParticipants(context.Context, *GetBattleParticipantsRequest) (*GetBattleParticipantsResponse, error)
	// Update participant stats
	UpdateParticipantStats(context.Context, *UpdateParticipantStatsRequest) (*UpdateParticipantStatsResponse, error)
	// Cast spell (called by other services if needed)
	CastSpell(context.Context, *CastSpellRequest) (*CastSpellResponse, error)
	mustEmbedUnimplementedBattleServiceServer()
}

// UnimplementedBattleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleServiceServer struct{}

func (UnimplementedBattleServiceServer) GetBattleByID(context.Context, *GetBattleByIDRequest) (*GetBattleByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBattleByID not implemented")
}
func (UnimplementedBattleServiceServer) GetActiveBattles(context.Context, *GetActiveBattlesRequest) (*GetActiveBattlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveBattles not implemented")
}
func (UnimplementedBattleServiceServer) GetBattleParticipants(context.Context, *GetBattleParticipantsRequest) (*GetBattleParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBattleParticipants not implemented")
}
func (UnimplementedBattleServiceServer) UpdateParticipantStats(context.Context, *UpdateParticipantStatsRequest) (*UpdateParticipantStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParticipantStats not implemented")
}
func (UnimplementedBattleServiceServer) CastSpell(context.Context, *CastSpellRequest) (*CastSpellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastSpell not implemented")
}
func (UnimplementedBattleServiceServer) mustEmbedUnimplementedBattleServiceServer() {}
func (UnimplementedBattleServiceServer) testEmbeddedByValue()                       {}

// UnsafeBattleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleServiceServer will
// result in compilation errors.
type UnsafeBattleServiceServer interface {
	mustEmbedUnimplementedBattleServiceServer()
}

func RegisterBattleServiceServer(s grpc.ServiceRegistrar, srv BattleServiceServer) {
	// If the following call pancis, it indicates UnimplementedBattleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleService_ServiceDesc, srv)
}

func _BattleService_GetBattleByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBattleByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).GetBattleByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_GetBattleByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).GetBattleByID(ctx, req.(*GetBattleByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_GetActiveBattles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveBattlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).GetActiveBattles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_GetActiveBattles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).GetActiveBattles(ctx, req.(*GetActiveBattlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_GetBattleParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBattleParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).GetBattleParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_GetBattleParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).GetBattleParticipants(ctx, req.(*GetBattleParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_UpdateParticipantStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParticipantStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).UpdateParticipantStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_UpdateParticipantStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).UpdateParticipantStats(ctx, req.(*UpdateParticipantStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_CastSpell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastSpellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).CastSpell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_CastSpell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).CastSpell(ctx, req.(*CastSpellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BattleService_ServiceDesc is the grpc.ServiceDesc for BattleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battle.BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBattleByID",
			Handler:    _BattleService_GetBattleByID_Handler,
		},
		{
			MethodName: "GetActiveBattles",
			Handler:    _BattleService_GetActiveBattles_Handler,
		},
		{
			MethodName: "GetBattleParticipants",
			Handler:    _BattleService_GetBattleParticipants_Handler,
		},
		{
			MethodName: "UpdateParticipantStats",
			Handler:    _BattleService_UpdateParticipantStats_Handler,
		},
		{
			MethodName: "CastSpell",
			Handler:    _BattleService_CastSpell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/battle/battle.proto",
}
