// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/warrior/warrior.proto

package warrior

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get warrior by username
type GetWarriorByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByUsernameRequest) Reset() {
	*x = GetWarriorByUsernameRequest{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByUsernameRequest) ProtoMessage() {}

func (x *GetWarriorByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetWarriorByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{0}
}

func (x *GetWarriorByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response with warrior
type GetWarriorByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warrior       *Warrior               `protobuf:"bytes,1,opt,name=warrior,proto3" json:"warrior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByUsernameResponse) Reset() {
	*x = GetWarriorByUsernameResponse{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByUsernameResponse) ProtoMessage() {}

func (x *GetWarriorByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByUsernameResponse.ProtoReflect.Descriptor instead.
func (*GetWarriorByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{1}
}

func (x *GetWarriorByUsernameResponse) GetWarrior() *Warrior {
	if x != nil {
		return x.Warrior
	}
	return nil
}

// Request to get warrior by ID
type GetWarriorByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarriorId     uint32                 `protobuf:"varint,1,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByIDRequest) Reset() {
	*x = GetWarriorByIDRequest{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByIDRequest) ProtoMessage() {}

func (x *GetWarriorByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByIDRequest.ProtoReflect.Descriptor instead.
func (*GetWarriorByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{2}
}

func (x *GetWarriorByIDRequest) GetWarriorId() uint32 {
	if x != nil {
		return x.WarriorId
	}
	return 0
}

// Response with warrior
type GetWarriorByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warrior       *Warrior               `protobuf:"bytes,1,opt,name=warrior,proto3" json:"warrior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByIDResponse) Reset() {
	*x = GetWarriorByIDResponse{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByIDResponse) ProtoMessage() {}

func (x *GetWarriorByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByIDResponse.ProtoReflect.Descriptor instead.
func (*GetWarriorByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{3}
}

func (x *GetWarriorByIDResponse) GetWarrior() *Warrior {
	if x != nil {
		return x.Warrior
	}
	return nil
}

// Request to update power
type UpdateWarriorPowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarriorId     uint32                 `protobuf:"varint,1,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	TotalPower    int32                  `protobuf:"varint,2,opt,name=total_power,json=totalPower,proto3" json:"total_power,omitempty"`
	WeaponCount   int32                  `protobuf:"varint,3,opt,name=weapon_count,json=weaponCount,proto3" json:"weapon_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarriorPowerRequest) Reset() {
	*x = UpdateWarriorPowerRequest{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarriorPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarriorPowerRequest) ProtoMessage() {}

func (x *UpdateWarriorPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarriorPowerRequest.ProtoReflect.Descriptor instead.
func (*UpdateWarriorPowerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWarriorPowerRequest) GetWarriorId() uint32 {
	if x != nil {
		return x.WarriorId
	}
	return 0
}

func (x *UpdateWarriorPowerRequest) GetTotalPower() int32 {
	if x != nil {
		return x.TotalPower
	}
	return 0
}

func (x *UpdateWarriorPowerRequest) GetWeaponCount() int32 {
	if x != nil {
		return x.WeaponCount
	}
	return 0
}

// Response after updating power
type UpdateWarriorPowerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarriorPowerResponse) Reset() {
	*x = UpdateWarriorPowerResponse{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarriorPowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarriorPowerResponse) ProtoMessage() {}

func (x *UpdateWarriorPowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarriorPowerResponse.ProtoReflect.Descriptor instead.
func (*UpdateWarriorPowerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWarriorPowerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateWarriorPowerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to update HP
type UpdateWarriorHPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarriorId     uint32                 `protobuf:"varint,1,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	NewHp         int32                  `protobuf:"varint,2,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarriorHPRequest) Reset() {
	*x = UpdateWarriorHPRequest{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarriorHPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarriorHPRequest) ProtoMessage() {}

func (x *UpdateWarriorHPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarriorHPRequest.ProtoReflect.Descriptor instead.
func (*UpdateWarriorHPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWarriorHPRequest) GetWarriorId() uint32 {
	if x != nil {
		return x.WarriorId
	}
	return 0
}

func (x *UpdateWarriorHPRequest) GetNewHp() int32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

// Response after updating HP
type UpdateWarriorHPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OldHp         int32                  `protobuf:"varint,3,opt,name=old_hp,json=oldHp,proto3" json:"old_hp,omitempty"`
	NewHp         int32                  `protobuf:"varint,4,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarriorHPResponse) Reset() {
	*x = UpdateWarriorHPResponse{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarriorHPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarriorHPResponse) ProtoMessage() {}

func (x *UpdateWarriorHPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarriorHPResponse.ProtoReflect.Descriptor instead.
func (*UpdateWarriorHPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateWarriorHPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateWarriorHPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateWarriorHPResponse) GetOldHp() int32 {
	if x != nil {
		return x.OldHp
	}
	return 0
}

func (x *UpdateWarriorHPResponse) GetNewHp() int32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

// Request to update healing state
type UpdateWarriorHealingStateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WarriorId           uint32                 `protobuf:"varint,1,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	IsHealing           bool                   `protobuf:"varint,2,opt,name=is_healing,json=isHealing,proto3" json:"is_healing,omitempty"`
	HealingUntilSeconds int64                  `protobuf:"varint,3,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // Unix timestamp (0 if not healing)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateWarriorHealingStateRequest) Reset() {
	*x = UpdateWarriorHealingStateRequest{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarriorHealingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarriorHealingStateRequest) ProtoMessage() {}

func (x *UpdateWarriorHealingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarriorHealingStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateWarriorHealingStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWarriorHealingStateRequest) GetWarriorId() uint32 {
	if x != nil {
		return x.WarriorId
	}
	return 0
}

func (x *UpdateWarriorHealingStateRequest) GetIsHealing() bool {
	if x != nil {
		return x.IsHealing
	}
	return false
}

func (x *UpdateWarriorHealingStateRequest) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

// Response after updating healing state
type UpdateWarriorHealingStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarriorHealingStateResponse) Reset() {
	*x = UpdateWarriorHealingStateResponse{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarriorHealingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarriorHealingStateResponse) ProtoMessage() {}

func (x *UpdateWarriorHealingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarriorHealingStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateWarriorHealingStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateWarriorHealingStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateWarriorHealingStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Warrior model
type Warrior struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username            string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email               string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role                string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CoinBalance         int32                  `protobuf:"varint,5,opt,name=coin_balance,json=coinBalance,proto3" json:"coin_balance,omitempty"`
	TotalPower          int32                  `protobuf:"varint,6,opt,name=total_power,json=totalPower,proto3" json:"total_power,omitempty"`
	WeaponCount         int32                  `protobuf:"varint,7,opt,name=weapon_count,json=weaponCount,proto3" json:"weapon_count,omitempty"`
	CurrentHp           int32                  `protobuf:"varint,8,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`                                  // Current HP (for healing)
	MaxHp               int32                  `protobuf:"varint,9,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`                                              // Maximum HP (calculated from total_power)
	IsHealing           bool                   `protobuf:"varint,10,opt,name=is_healing,json=isHealing,proto3" json:"is_healing,omitempty"`                                 // Is currently healing
	HealingUntilSeconds int64                  `protobuf:"varint,11,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // Unix timestamp when healing completes (0 if not healing)
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Warrior) Reset() {
	*x = Warrior{}
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warrior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warrior) ProtoMessage() {}

func (x *Warrior) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_warrior_warrior_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warrior.ProtoReflect.Descriptor instead.
func (*Warrior) Descriptor() ([]byte, []int) {
	return file_api_proto_warrior_warrior_proto_rawDescGZIP(), []int{10}
}

func (x *Warrior) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warrior) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Warrior) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Warrior) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Warrior) GetCoinBalance() int32 {
	if x != nil {
		return x.CoinBalance
	}
	return 0
}

func (x *Warrior) GetTotalPower() int32 {
	if x != nil {
		return x.TotalPower
	}
	return 0
}

func (x *Warrior) GetWeaponCount() int32 {
	if x != nil {
		return x.WeaponCount
	}
	return 0
}

func (x *Warrior) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *Warrior) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Warrior) GetIsHealing() bool {
	if x != nil {
		return x.IsHealing
	}
	return false
}

func (x *Warrior) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

func (x *Warrior) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Warrior) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_proto_warrior_warrior_proto protoreflect.FileDescriptor

const file_api_proto_warrior_warrior_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/warrior/warrior.proto\x12\awarrior\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x1bGetWarriorByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"J\n" +
	"\x1cGetWarriorByUsernameResponse\x12*\n" +
	"\awarrior\x18\x01 \x01(\v2\x10.warrior.WarriorR\awarrior\"6\n" +
	"\x15GetWarriorByIDRequest\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x01 \x01(\rR\twarriorId\"D\n" +
	"\x16GetWarriorByIDResponse\x12*\n" +
	"\awarrior\x18\x01 \x01(\v2\x10.warrior.WarriorR\awarrior\"~\n" +
	"\x19UpdateWarriorPowerRequest\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x01 \x01(\rR\twarriorId\x12\x1f\n" +
	"\vtotal_power\x18\x02 \x01(\x05R\n" +
	"totalPower\x12!\n" +
	"\fweapon_count\x18\x03 \x01(\x05R\vweaponCount\"P\n" +
	"\x1aUpdateWarriorPowerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x16UpdateWarriorHPRequest\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x01 \x01(\rR\twarriorId\x12\x15\n" +
	"\x06new_hp\x18\x02 \x01(\x05R\x05newHp\"{\n" +
	"\x17UpdateWarriorHPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06old_hp\x18\x03 \x01(\x05R\x05oldHp\x12\x15\n" +
	"\x06new_hp\x18\x04 \x01(\x05R\x05newHp\"\x94\x01\n" +
	" UpdateWarriorHealingStateRequest\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x01 \x01(\rR\twarriorId\x12\x1d\n" +
	"\n" +
	"is_healing\x18\x02 \x01(\bR\tisHealing\x122\n" +
	"\x15healing_until_seconds\x18\x03 \x01(\x03R\x13healingUntilSeconds\"W\n" +
	"!UpdateWarriorHealingStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc5\x03\n" +
	"\aWarrior\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12!\n" +
	"\fcoin_balance\x18\x05 \x01(\x05R\vcoinBalance\x12\x1f\n" +
	"\vtotal_power\x18\x06 \x01(\x05R\n" +
	"totalPower\x12!\n" +
	"\fweapon_count\x18\a \x01(\x05R\vweaponCount\x12\x1d\n" +
	"\n" +
	"current_hp\x18\b \x01(\x05R\tcurrentHp\x12\x15\n" +
	"\x06max_hp\x18\t \x01(\x05R\x05maxHp\x12\x1d\n" +
	"\n" +
	"is_healing\x18\n" +
	" \x01(\bR\tisHealing\x122\n" +
	"\x15healing_until_seconds\x18\v \x01(\x03R\x13healingUntilSeconds\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xf1\x03\n" +
	"\x0eWarriorService\x12c\n" +
	"\x14GetWarriorByUsername\x12$.warrior.GetWarriorByUsernameRequest\x1a%.warrior.GetWarriorByUsernameResponse\x12Q\n" +
	"\x0eGetWarriorByID\x12\x1e.warrior.GetWarriorByIDRequest\x1a\x1f.warrior.GetWarriorByIDResponse\x12]\n" +
	"\x12UpdateWarriorPower\x12\".warrior.UpdateWarriorPowerRequest\x1a#.warrior.UpdateWarriorPowerResponse\x12T\n" +
	"\x0fUpdateWarriorHP\x12\x1f.warrior.UpdateWarriorHPRequest\x1a .warrior.UpdateWarriorHPResponse\x12r\n" +
	"\x19UpdateWarriorHealingState\x12).warrior.UpdateWarriorHealingStateRequest\x1a*.warrior.UpdateWarriorHealingStateResponseB%Z#network-sec-micro/api/proto/warriorb\x06proto3"

var (
	file_api_proto_warrior_warrior_proto_rawDescOnce sync.Once
	file_api_proto_warrior_warrior_proto_rawDescData []byte
)

func file_api_proto_warrior_warrior_proto_rawDescGZIP() []byte {
	file_api_proto_warrior_warrior_proto_rawDescOnce.Do(func() {
		file_api_proto_warrior_warrior_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_warrior_warrior_proto_rawDesc), len(file_api_proto_warrior_warrior_proto_rawDesc)))
	})
	return file_api_proto_warrior_warrior_proto_rawDescData
}

var file_api_proto_warrior_warrior_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_warrior_warrior_proto_goTypes = []any{
	(*GetWarriorByUsernameRequest)(nil),       // 0: warrior.GetWarriorByUsernameRequest
	(*GetWarriorByUsernameResponse)(nil),      // 1: warrior.GetWarriorByUsernameResponse
	(*GetWarriorByIDRequest)(nil),             // 2: warrior.GetWarriorByIDRequest
	(*GetWarriorByIDResponse)(nil),            // 3: warrior.GetWarriorByIDResponse
	(*UpdateWarriorPowerRequest)(nil),         // 4: warrior.UpdateWarriorPowerRequest
	(*UpdateWarriorPowerResponse)(nil),        // 5: warrior.UpdateWarriorPowerResponse
	(*UpdateWarriorHPRequest)(nil),            // 6: warrior.UpdateWarriorHPRequest
	(*UpdateWarriorHPResponse)(nil),           // 7: warrior.UpdateWarriorHPResponse
	(*UpdateWarriorHealingStateRequest)(nil),  // 8: warrior.UpdateWarriorHealingStateRequest
	(*UpdateWarriorHealingStateResponse)(nil), // 9: warrior.UpdateWarriorHealingStateResponse
	(*Warrior)(nil),                           // 10: warrior.Warrior
	(*timestamppb.Timestamp)(nil),             // 11: google.protobuf.Timestamp
}
var file_api_proto_warrior_warrior_proto_depIdxs = []int32{
	10, // 0: warrior.GetWarriorByUsernameResponse.warrior:type_name -> warrior.Warrior
	10, // 1: warrior.GetWarriorByIDResponse.warrior:type_name -> warrior.Warrior
	11, // 2: warrior.Warrior.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: warrior.Warrior.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: warrior.WarriorService.GetWarriorByUsername:input_type -> warrior.GetWarriorByUsernameRequest
	2,  // 5: warrior.WarriorService.GetWarriorByID:input_type -> warrior.GetWarriorByIDRequest
	4,  // 6: warrior.WarriorService.UpdateWarriorPower:input_type -> warrior.UpdateWarriorPowerRequest
	6,  // 7: warrior.WarriorService.UpdateWarriorHP:input_type -> warrior.UpdateWarriorHPRequest
	8,  // 8: warrior.WarriorService.UpdateWarriorHealingState:input_type -> warrior.UpdateWarriorHealingStateRequest
	1,  // 9: warrior.WarriorService.GetWarriorByUsername:output_type -> warrior.GetWarriorByUsernameResponse
	3,  // 10: warrior.WarriorService.GetWarriorByID:output_type -> warrior.GetWarriorByIDResponse
	5,  // 11: warrior.WarriorService.UpdateWarriorPower:output_type -> warrior.UpdateWarriorPowerResponse
	7,  // 12: warrior.WarriorService.UpdateWarriorHP:output_type -> warrior.UpdateWarriorHPResponse
	9,  // 13: warrior.WarriorService.UpdateWarriorHealingState:output_type -> warrior.UpdateWarriorHealingStateResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_warrior_warrior_proto_init() }
func file_api_proto_warrior_warrior_proto_init() {
	if File_api_proto_warrior_warrior_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_warrior_warrior_proto_rawDesc), len(file_api_proto_warrior_warrior_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_warrior_warrior_proto_goTypes,
		DependencyIndexes: file_api_proto_warrior_warrior_proto_depIdxs,
		MessageInfos:      file_api_proto_warrior_warrior_proto_msgTypes,
	}.Build()
	File_api_proto_warrior_warrior_proto = out.File
	file_api_proto_warrior_warrior_proto_goTypes = nil
	file_api_proto_warrior_warrior_proto_depIdxs = nil
}
