// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"network-sec-micro/internal/heal"
)

// Injectors from wire.go:

func InitializeApp() (*heal.Service, *heal.HealServiceServer, error) {
	service := heal.NewService()
	healServiceServer := heal.NewHealServiceServer(service)
	return service, healServiceServer, nil
}

