// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/arena/arena.proto

package arena

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArenaService_GetWarriorByUsername_FullMethodName = "/arena.ArenaService/GetWarriorByUsername"
	ArenaService_GetWarriorByID_FullMethodName       = "/arena.ArenaService/GetWarriorByID"
)

// ArenaServiceClient is the client API for ArenaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Arena Service (gRPC methods for service-to-service communication)
type ArenaServiceClient interface {
	// Get warrior info by username (for invitation validation)
	GetWarriorByUsername(ctx context.Context, in *GetWarriorByUsernameRequest, opts ...grpc.CallOption) (*GetWarriorByUsernameResponse, error)
	// Get warrior info by ID (for match creation)
	GetWarriorByID(ctx context.Context, in *GetWarriorByIDRequest, opts ...grpc.CallOption) (*GetWarriorByIDResponse, error)
}

type arenaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArenaServiceClient(cc grpc.ClientConnInterface) ArenaServiceClient {
	return &arenaServiceClient{cc}
}

func (c *arenaServiceClient) GetWarriorByUsername(ctx context.Context, in *GetWarriorByUsernameRequest, opts ...grpc.CallOption) (*GetWarriorByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWarriorByUsernameResponse)
	err := c.cc.Invoke(ctx, ArenaService_GetWarriorByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) GetWarriorByID(ctx context.Context, in *GetWarriorByIDRequest, opts ...grpc.CallOption) (*GetWarriorByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWarriorByIDResponse)
	err := c.cc.Invoke(ctx, ArenaService_GetWarriorByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaServiceServer is the server API for ArenaService service.
// All implementations must embed UnimplementedArenaServiceServer
// for forward compatibility.
//
// Arena Service (gRPC methods for service-to-service communication)
type ArenaServiceServer interface {
	// Get warrior info by username (for invitation validation)
	GetWarriorByUsername(context.Context, *GetWarriorByUsernameRequest) (*GetWarriorByUsernameResponse, error)
	// Get warrior info by ID (for match creation)
	GetWarriorByID(context.Context, *GetWarriorByIDRequest) (*GetWarriorByIDResponse, error)
	mustEmbedUnimplementedArenaServiceServer()
}

// UnimplementedArenaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArenaServiceServer struct{}

func (UnimplementedArenaServiceServer) GetWarriorByUsername(context.Context, *GetWarriorByUsernameRequest) (*GetWarriorByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWarriorByUsername not implemented")
}
func (UnimplementedArenaServiceServer) GetWarriorByID(context.Context, *GetWarriorByIDRequest) (*GetWarriorByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWarriorByID not implemented")
}
func (UnimplementedArenaServiceServer) mustEmbedUnimplementedArenaServiceServer() {}
func (UnimplementedArenaServiceServer) testEmbeddedByValue()                      {}

// UnsafeArenaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArenaServiceServer will
// result in compilation errors.
type UnsafeArenaServiceServer interface {
	mustEmbedUnimplementedArenaServiceServer()
}

func RegisterArenaServiceServer(s grpc.ServiceRegistrar, srv ArenaServiceServer) {
	// If the following call pancis, it indicates UnimplementedArenaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArenaService_ServiceDesc, srv)
}

func _ArenaService_GetWarriorByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWarriorByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).GetWarriorByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_GetWarriorByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).GetWarriorByUsername(ctx, req.(*GetWarriorByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_GetWarriorByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWarriorByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).GetWarriorByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_GetWarriorByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).GetWarriorByID(ctx, req.(*GetWarriorByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArenaService_ServiceDesc is the grpc.ServiceDesc for ArenaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArenaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arena.ArenaService",
	HandlerType: (*ArenaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWarriorByUsername",
			Handler:    _ArenaService_GetWarriorByUsername_Handler,
		},
		{
			MethodName: "GetWarriorByID",
			Handler:    _ArenaService_GetWarriorByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/arena/arena.proto",
}
