// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/arena/arena.proto

package arena

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get warrior by username
type GetWarriorByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByUsernameRequest) Reset() {
	*x = GetWarriorByUsernameRequest{}
	mi := &file_api_proto_arena_arena_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByUsernameRequest) ProtoMessage() {}

func (x *GetWarriorByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arena_arena_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetWarriorByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_arena_arena_proto_rawDescGZIP(), []int{0}
}

func (x *GetWarriorByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response with warrior info
type GetWarriorByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warrior       *Warrior               `protobuf:"bytes,1,opt,name=warrior,proto3" json:"warrior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByUsernameResponse) Reset() {
	*x = GetWarriorByUsernameResponse{}
	mi := &file_api_proto_arena_arena_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByUsernameResponse) ProtoMessage() {}

func (x *GetWarriorByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arena_arena_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByUsernameResponse.ProtoReflect.Descriptor instead.
func (*GetWarriorByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_arena_arena_proto_rawDescGZIP(), []int{1}
}

func (x *GetWarriorByUsernameResponse) GetWarrior() *Warrior {
	if x != nil {
		return x.Warrior
	}
	return nil
}

// Request to get warrior by ID
type GetWarriorByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarriorId     uint32                 `protobuf:"varint,1,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByIDRequest) Reset() {
	*x = GetWarriorByIDRequest{}
	mi := &file_api_proto_arena_arena_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByIDRequest) ProtoMessage() {}

func (x *GetWarriorByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arena_arena_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByIDRequest.ProtoReflect.Descriptor instead.
func (*GetWarriorByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_arena_arena_proto_rawDescGZIP(), []int{2}
}

func (x *GetWarriorByIDRequest) GetWarriorId() uint32 {
	if x != nil {
		return x.WarriorId
	}
	return 0
}

// Response with warrior info
type GetWarriorByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warrior       *Warrior               `protobuf:"bytes,1,opt,name=warrior,proto3" json:"warrior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarriorByIDResponse) Reset() {
	*x = GetWarriorByIDResponse{}
	mi := &file_api_proto_arena_arena_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarriorByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarriorByIDResponse) ProtoMessage() {}

func (x *GetWarriorByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arena_arena_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarriorByIDResponse.ProtoReflect.Descriptor instead.
func (*GetWarriorByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_arena_arena_proto_rawDescGZIP(), []int{3}
}

func (x *GetWarriorByIDResponse) GetWarrior() *Warrior {
	if x != nil {
		return x.Warrior
	}
	return nil
}

// Warrior information
type Warrior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	TotalPower    int32                  `protobuf:"varint,5,opt,name=total_power,json=totalPower,proto3" json:"total_power,omitempty"`
	AttackPower   int32                  `protobuf:"varint,6,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Defense       int32                  `protobuf:"varint,7,opt,name=defense,proto3" json:"defense,omitempty"`
	CoinBalance   int32                  `protobuf:"varint,8,opt,name=coin_balance,json=coinBalance,proto3" json:"coin_balance,omitempty"`
	WeaponCount   int32                  `protobuf:"varint,9,opt,name=weapon_count,json=weaponCount,proto3" json:"weapon_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warrior) Reset() {
	*x = Warrior{}
	mi := &file_api_proto_arena_arena_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warrior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warrior) ProtoMessage() {}

func (x *Warrior) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arena_arena_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warrior.ProtoReflect.Descriptor instead.
func (*Warrior) Descriptor() ([]byte, []int) {
	return file_api_proto_arena_arena_proto_rawDescGZIP(), []int{4}
}

func (x *Warrior) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warrior) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Warrior) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Warrior) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Warrior) GetTotalPower() int32 {
	if x != nil {
		return x.TotalPower
	}
	return 0
}

func (x *Warrior) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *Warrior) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *Warrior) GetCoinBalance() int32 {
	if x != nil {
		return x.CoinBalance
	}
	return 0
}

func (x *Warrior) GetWeaponCount() int32 {
	if x != nil {
		return x.WeaponCount
	}
	return 0
}

var File_api_proto_arena_arena_proto protoreflect.FileDescriptor

const file_api_proto_arena_arena_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/arena/arena.proto\x12\x05arena\"9\n" +
	"\x1bGetWarriorByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"H\n" +
	"\x1cGetWarriorByUsernameResponse\x12(\n" +
	"\awarrior\x18\x01 \x01(\v2\x0e.arena.WarriorR\awarrior\"6\n" +
	"\x15GetWarriorByIDRequest\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x01 \x01(\rR\twarriorId\"B\n" +
	"\x16GetWarriorByIDResponse\x12(\n" +
	"\awarrior\x18\x01 \x01(\v2\x0e.arena.WarriorR\awarrior\"\x83\x02\n" +
	"\aWarrior\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1f\n" +
	"\vtotal_power\x18\x05 \x01(\x05R\n" +
	"totalPower\x12!\n" +
	"\fattack_power\x18\x06 \x01(\x05R\vattackPower\x12\x18\n" +
	"\adefense\x18\a \x01(\x05R\adefense\x12!\n" +
	"\fcoin_balance\x18\b \x01(\x05R\vcoinBalance\x12!\n" +
	"\fweapon_count\x18\t \x01(\x05R\vweaponCount2\xbe\x01\n" +
	"\fArenaService\x12_\n" +
	"\x14GetWarriorByUsername\x12\".arena.GetWarriorByUsernameRequest\x1a#.arena.GetWarriorByUsernameResponse\x12M\n" +
	"\x0eGetWarriorByID\x12\x1c.arena.GetWarriorByIDRequest\x1a\x1d.arena.GetWarriorByIDResponseB#Z!network-sec-micro/api/proto/arenab\x06proto3"

var (
	file_api_proto_arena_arena_proto_rawDescOnce sync.Once
	file_api_proto_arena_arena_proto_rawDescData []byte
)

func file_api_proto_arena_arena_proto_rawDescGZIP() []byte {
	file_api_proto_arena_arena_proto_rawDescOnce.Do(func() {
		file_api_proto_arena_arena_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_arena_arena_proto_rawDesc), len(file_api_proto_arena_arena_proto_rawDesc)))
	})
	return file_api_proto_arena_arena_proto_rawDescData
}

var file_api_proto_arena_arena_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_arena_arena_proto_goTypes = []any{
	(*GetWarriorByUsernameRequest)(nil),  // 0: arena.GetWarriorByUsernameRequest
	(*GetWarriorByUsernameResponse)(nil), // 1: arena.GetWarriorByUsernameResponse
	(*GetWarriorByIDRequest)(nil),        // 2: arena.GetWarriorByIDRequest
	(*GetWarriorByIDResponse)(nil),       // 3: arena.GetWarriorByIDResponse
	(*Warrior)(nil),                      // 4: arena.Warrior
}
var file_api_proto_arena_arena_proto_depIdxs = []int32{
	4, // 0: arena.GetWarriorByUsernameResponse.warrior:type_name -> arena.Warrior
	4, // 1: arena.GetWarriorByIDResponse.warrior:type_name -> arena.Warrior
	0, // 2: arena.ArenaService.GetWarriorByUsername:input_type -> arena.GetWarriorByUsernameRequest
	2, // 3: arena.ArenaService.GetWarriorByID:input_type -> arena.GetWarriorByIDRequest
	1, // 4: arena.ArenaService.GetWarriorByUsername:output_type -> arena.GetWarriorByUsernameResponse
	3, // 5: arena.ArenaService.GetWarriorByID:output_type -> arena.GetWarriorByIDResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_arena_arena_proto_init() }
func file_api_proto_arena_arena_proto_init() {
	if File_api_proto_arena_arena_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_arena_arena_proto_rawDesc), len(file_api_proto_arena_arena_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_arena_arena_proto_goTypes,
		DependencyIndexes: file_api_proto_arena_arena_proto_depIdxs,
		MessageInfos:      file_api_proto_arena_arena_proto_msgTypes,
	}.Build()
	File_api_proto_arena_arena_proto = out.File
	file_api_proto_arena_arena_proto_goTypes = nil
	file_api_proto_arena_arena_proto_depIdxs = nil
}
