apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.coin }}
  selector:
    matchLabels:
      app: coin
  template:
    metadata:
      labels:
        app: coin
    spec:
      containers:
        - name: coin
          image: {{ .Values.images.coin.repository }}:{{ .Values.images.coin.tag }}
          imagePullPolicy: {{ .Values.images.coin.pullPolicy }}
          env:
            - { name: DB_HOST, value: {{ .Values.env.mysql.host | quote }} }
            - { name: DB_PORT, value: {{ .Values.env.mysql.port | quote }} }
            - { name: DB_USER, value: {{ .Values.env.mysql.user | quote }} }
            - { name: DB_PASSWORD, value: {{ .Values.env.mysql.password | quote }} }
            - { name: DB_NAME, value: {{ .Values.env.mysql.db | quote }} }
            - { name: DB_CHARSET, value: "utf8mb4" }
            - { name: DB_PARSE_TIME, value: "true" }
            - { name: DB_LOC, value: "Local" }
            - { name: GRPC_PORT, value: "50051" }
            - { name: KAFKA_BROKERS, value: {{ .Values.env.kafkaBrokers | quote }} }
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: coin
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: coin
  ports:
    - port: 50051
      targetPort: 50051

