apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiber-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.gateway }}
  selector:
    matchLabels:
      app: fiber-gateway
  template:
    metadata:
      labels:
        app: fiber-gateway
    spec:
      containers:
        - name: fiber-gateway
          image: {{ .Values.images.gateway.repository }}:{{ .Values.images.gateway.tag }}
          imagePullPolicy: {{ .Values.images.gateway.pullPolicy }}
          env:
            - { name: GW_PORT, value: "8090" }
            - { name: UPSTREAM_WARRIOR, value: "http://warrior:8080" }
            - { name: UPSTREAM_ENEMY, value: "http://enemy:8083" }
            - { name: UPSTREAM_DRAGON, value: "http://dragon:8084" }
            - { name: UPSTREAM_WEAPON, value: "http://weapon:8081" }
            - { name: REDIS_ADDR, value: {{ .Values.env.redisAddr | quote }} }
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: fiber-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fiber-gateway
  ports:
    - port: 8090
      targetPort: 8090
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiber-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "nginx" }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fiber-gateway
                port:
                  number: 8090
{{- end }}

