apiVersion: apps/v1
kind: Deployment
metadata:
  name: warrior
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.warrior }}
  selector:
    matchLabels:
      app: warrior
  template:
    metadata:
      labels:
        app: warrior
    spec:
      containers:
        - name: warrior
          image: {{ .Values.images.warrior.repository }}:{{ .Values.images.warrior.tag }}
          imagePullPolicy: {{ .Values.images.warrior.pullPolicy }}
          env:
            - { name: DB_HOST, value: {{ .Values.env.postgres.host | quote }} }
            - { name: DB_PORT, value: {{ .Values.env.postgres.port | quote }} }
            - { name: DB_USER, value: {{ .Values.env.postgres.user | quote }} }
            - { name: DB_PASSWORD, value: {{ .Values.env.postgres.password | quote }} }
            - { name: DB_NAME, value: {{ .Values.env.postgres.db | quote }} }
            - { name: DB_SSLMODE, value: "disable" }
            - { name: PORT, value: "8080" }
            - { name: GIN_MODE, value: "release" }
            - { name: KAFKA_BROKERS, value: {{ .Values.env.kafkaBrokers | quote }} }
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: warrior
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: warrior
  ports:
    - port: 8080
      targetPort: 8080

