// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/armor/armor.proto

package armor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get armor
type GetArmorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArmorId       string                 `protobuf:"bytes,1,opt,name=armor_id,json=armorId,proto3" json:"armor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmorRequest) Reset() {
	*x = GetArmorRequest{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmorRequest) ProtoMessage() {}

func (x *GetArmorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmorRequest.ProtoReflect.Descriptor instead.
func (*GetArmorRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{0}
}

func (x *GetArmorRequest) GetArmorId() string {
	if x != nil {
		return x.ArmorId
	}
	return ""
}

// Response with armor details
type GetArmorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Armor         *Armor                 `protobuf:"bytes,1,opt,name=armor,proto3" json:"armor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmorResponse) Reset() {
	*x = GetArmorResponse{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmorResponse) ProtoMessage() {}

func (x *GetArmorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmorResponse.ProtoReflect.Descriptor instead.
func (*GetArmorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{1}
}

func (x *GetArmorResponse) GetArmor() *Armor {
	if x != nil {
		return x.Armor
	}
	return nil
}

// Request to calculate defense
type CalculateDefenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     string                 `protobuf:"bytes,1,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"` // "warrior" | "enemy" | "dragon"
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`       // warrior username or entity id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDefenseRequest) Reset() {
	*x = CalculateDefenseRequest{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDefenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDefenseRequest) ProtoMessage() {}

func (x *CalculateDefenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDefenseRequest.ProtoReflect.Descriptor instead.
func (*CalculateDefenseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateDefenseRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CalculateDefenseRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// Response with calculated defense
type CalculateDefenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     string                 `protobuf:"bytes,1,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	BaseDefense   int32                  `protobuf:"varint,3,opt,name=base_defense,json=baseDefense,proto3" json:"base_defense,omitempty"`
	ArmorBonus    int32                  `protobuf:"varint,4,opt,name=armor_bonus,json=armorBonus,proto3" json:"armor_bonus,omitempty"`
	TotalDefense  int32                  `protobuf:"varint,5,opt,name=total_defense,json=totalDefense,proto3" json:"total_defense,omitempty"`
	ArmorCount    int32                  `protobuf:"varint,6,opt,name=armor_count,json=armorCount,proto3" json:"armor_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDefenseResponse) Reset() {
	*x = CalculateDefenseResponse{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDefenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDefenseResponse) ProtoMessage() {}

func (x *CalculateDefenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDefenseResponse.ProtoReflect.Descriptor instead.
func (*CalculateDefenseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateDefenseResponse) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CalculateDefenseResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CalculateDefenseResponse) GetBaseDefense() int32 {
	if x != nil {
		return x.BaseDefense
	}
	return 0
}

func (x *CalculateDefenseResponse) GetArmorBonus() int32 {
	if x != nil {
		return x.ArmorBonus
	}
	return 0
}

func (x *CalculateDefenseResponse) GetTotalDefense() int32 {
	if x != nil {
		return x.TotalDefense
	}
	return 0
}

func (x *CalculateDefenseResponse) GetArmorCount() int32 {
	if x != nil {
		return x.ArmorCount
	}
	return 0
}

// Armor model
type Armor struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type        string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "common", "rare", "legendary"
	Defense     int32                  `protobuf:"varint,5,opt,name=defense,proto3" json:"defense,omitempty"`
	HpBonus     int32                  `protobuf:"varint,6,opt,name=hp_bonus,json=hpBonus,proto3" json:"hp_bonus,omitempty"` // Additional HP provided by armor
	Price       int32                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	CreatedBy   string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	OwnedBy     []string               `protobuf:"bytes,9,rep,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"` // legacy warrior usernames
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Durability fields
	Durability    int32 `protobuf:"varint,12,opt,name=durability,proto3" json:"durability,omitempty"`                            // current durability (0..max_durability)
	MaxDurability int32 `protobuf:"varint,13,opt,name=max_durability,json=maxDurability,proto3" json:"max_durability,omitempty"` // maximum durability
	IsBroken      bool  `protobuf:"varint,14,opt,name=is_broken,json=isBroken,proto3" json:"is_broken,omitempty"`                // derived from durability == 0
	// Generalized ownership (supports warrior/enemy/dragon)
	Owners        []*OwnerRef `protobuf:"bytes,15,rep,name=owners,proto3" json:"owners,omitempty"` // when set, preferred over owned_by
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Armor) Reset() {
	*x = Armor{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Armor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Armor) ProtoMessage() {}

func (x *Armor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Armor.ProtoReflect.Descriptor instead.
func (*Armor) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{4}
}

func (x *Armor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Armor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Armor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Armor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Armor) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *Armor) GetHpBonus() int32 {
	if x != nil {
		return x.HpBonus
	}
	return 0
}

func (x *Armor) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Armor) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Armor) GetOwnedBy() []string {
	if x != nil {
		return x.OwnedBy
	}
	return nil
}

func (x *Armor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Armor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Armor) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *Armor) GetMaxDurability() int32 {
	if x != nil {
		return x.MaxDurability
	}
	return 0
}

func (x *Armor) GetIsBroken() bool {
	if x != nil {
		return x.IsBroken
	}
	return false
}

func (x *Armor) GetOwners() []*OwnerRef {
	if x != nil {
		return x.Owners
	}
	return nil
}

// Owner reference to support multiple entity types
type OwnerRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     string                 `protobuf:"bytes,1,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"` // "warrior" | "enemy" | "dragon"
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`       // id or username depending on type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerRef) Reset() {
	*x = OwnerRef{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerRef) ProtoMessage() {}

func (x *OwnerRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerRef.ProtoReflect.Descriptor instead.
func (*OwnerRef) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{5}
}

func (x *OwnerRef) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *OwnerRef) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// Request to list armors by owner
type ListOwnerArmorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     string                 `protobuf:"bytes,1,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"` // "warrior" | "enemy" | "dragon"
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`       // warrior username or entity id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnerArmorsRequest) Reset() {
	*x = ListOwnerArmorsRequest{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnerArmorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnerArmorsRequest) ProtoMessage() {}

func (x *ListOwnerArmorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnerArmorsRequest.ProtoReflect.Descriptor instead.
func (*ListOwnerArmorsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{6}
}

func (x *ListOwnerArmorsRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *ListOwnerArmorsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// Response listing owner's armors
type ListOwnerArmorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Armors        []*Armor               `protobuf:"bytes,1,rep,name=armors,proto3" json:"armors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnerArmorsResponse) Reset() {
	*x = ListOwnerArmorsResponse{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnerArmorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnerArmorsResponse) ProtoMessage() {}

func (x *ListOwnerArmorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnerArmorsResponse.ProtoReflect.Descriptor instead.
func (*ListOwnerArmorsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{7}
}

func (x *ListOwnerArmorsResponse) GetArmors() []*Armor {
	if x != nil {
		return x.Armors
	}
	return nil
}

// Request to apply wear to an armor
type ApplyWearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArmorId       string                 `protobuf:"bytes,1,opt,name=armor_id,json=armorId,proto3" json:"armor_id,omitempty"`
	Wear          int32                  `protobuf:"varint,2,opt,name=wear,proto3" json:"wear,omitempty"` // how much durability to reduce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWearRequest) Reset() {
	*x = ApplyWearRequest{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWearRequest) ProtoMessage() {}

func (x *ApplyWearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWearRequest.ProtoReflect.Descriptor instead.
func (*ApplyWearRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyWearRequest) GetArmorId() string {
	if x != nil {
		return x.ArmorId
	}
	return ""
}

func (x *ApplyWearRequest) GetWear() int32 {
	if x != nil {
		return x.Wear
	}
	return 0
}

// Response after applying wear
type ApplyWearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArmorId       string                 `protobuf:"bytes,1,opt,name=armor_id,json=armorId,proto3" json:"armor_id,omitempty"`
	Durability    int32                  `protobuf:"varint,2,opt,name=durability,proto3" json:"durability,omitempty"`
	IsBroken      bool                   `protobuf:"varint,3,opt,name=is_broken,json=isBroken,proto3" json:"is_broken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWearResponse) Reset() {
	*x = ApplyWearResponse{}
	mi := &file_api_proto_armor_armor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWearResponse) ProtoMessage() {}

func (x *ApplyWearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_armor_armor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWearResponse.ProtoReflect.Descriptor instead.
func (*ApplyWearResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_armor_armor_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyWearResponse) GetArmorId() string {
	if x != nil {
		return x.ArmorId
	}
	return ""
}

func (x *ApplyWearResponse) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *ApplyWearResponse) GetIsBroken() bool {
	if x != nil {
		return x.IsBroken
	}
	return false
}

var File_api_proto_armor_armor_proto protoreflect.FileDescriptor

const file_api_proto_armor_armor_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/armor/armor.proto\x12\x05armor\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x0fGetArmorRequest\x12\x19\n" +
	"\barmor_id\x18\x01 \x01(\tR\aarmorId\"6\n" +
	"\x10GetArmorResponse\x12\"\n" +
	"\x05armor\x18\x01 \x01(\v2\f.armor.ArmorR\x05armor\"S\n" +
	"\x17CalculateDefenseRequest\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"\xde\x01\n" +
	"\x18CalculateDefenseResponse\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12!\n" +
	"\fbase_defense\x18\x03 \x01(\x05R\vbaseDefense\x12\x1f\n" +
	"\varmor_bonus\x18\x04 \x01(\x05R\n" +
	"armorBonus\x12#\n" +
	"\rtotal_defense\x18\x05 \x01(\x05R\ftotalDefense\x12\x1f\n" +
	"\varmor_count\x18\x06 \x01(\x05R\n" +
	"armorCount\"\xe9\x03\n" +
	"\x05Armor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\adefense\x18\x05 \x01(\x05R\adefense\x12\x19\n" +
	"\bhp_bonus\x18\x06 \x01(\x05R\ahpBonus\x12\x14\n" +
	"\x05price\x18\a \x01(\x05R\x05price\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x12\x19\n" +
	"\bowned_by\x18\t \x03(\tR\aownedBy\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1e\n" +
	"\n" +
	"durability\x18\f \x01(\x05R\n" +
	"durability\x12%\n" +
	"\x0emax_durability\x18\r \x01(\x05R\rmaxDurability\x12\x1b\n" +
	"\tis_broken\x18\x0e \x01(\bR\bisBroken\x12'\n" +
	"\x06owners\x18\x0f \x03(\v2\x0f.armor.OwnerRefR\x06owners\"D\n" +
	"\bOwnerRef\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"R\n" +
	"\x16ListOwnerArmorsRequest\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"?\n" +
	"\x17ListOwnerArmorsResponse\x12$\n" +
	"\x06armors\x18\x01 \x03(\v2\f.armor.ArmorR\x06armors\"A\n" +
	"\x10ApplyWearRequest\x12\x19\n" +
	"\barmor_id\x18\x01 \x01(\tR\aarmorId\x12\x12\n" +
	"\x04wear\x18\x02 \x01(\x05R\x04wear\"k\n" +
	"\x11ApplyWearResponse\x12\x19\n" +
	"\barmor_id\x18\x01 \x01(\tR\aarmorId\x12\x1e\n" +
	"\n" +
	"durability\x18\x02 \x01(\x05R\n" +
	"durability\x12\x1b\n" +
	"\tis_broken\x18\x03 \x01(\bR\bisBroken2\xb2\x02\n" +
	"\fArmorService\x12;\n" +
	"\bGetArmor\x12\x16.armor.GetArmorRequest\x1a\x17.armor.GetArmorResponse\x12S\n" +
	"\x10CalculateDefense\x12\x1e.armor.CalculateDefenseRequest\x1a\x1f.armor.CalculateDefenseResponse\x12P\n" +
	"\x0fListOwnerArmors\x12\x1d.armor.ListOwnerArmorsRequest\x1a\x1e.armor.ListOwnerArmorsResponse\x12>\n" +
	"\tApplyWear\x12\x17.armor.ApplyWearRequest\x1a\x18.armor.ApplyWearResponseB#Z!network-sec-micro/api/proto/armorb\x06proto3"

var (
	file_api_proto_armor_armor_proto_rawDescOnce sync.Once
	file_api_proto_armor_armor_proto_rawDescData []byte
)

func file_api_proto_armor_armor_proto_rawDescGZIP() []byte {
	file_api_proto_armor_armor_proto_rawDescOnce.Do(func() {
		file_api_proto_armor_armor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_armor_armor_proto_rawDesc), len(file_api_proto_armor_armor_proto_rawDesc)))
	})
	return file_api_proto_armor_armor_proto_rawDescData
}

var file_api_proto_armor_armor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_armor_armor_proto_goTypes = []any{
	(*GetArmorRequest)(nil),          // 0: armor.GetArmorRequest
	(*GetArmorResponse)(nil),         // 1: armor.GetArmorResponse
	(*CalculateDefenseRequest)(nil),  // 2: armor.CalculateDefenseRequest
	(*CalculateDefenseResponse)(nil), // 3: armor.CalculateDefenseResponse
	(*Armor)(nil),                    // 4: armor.Armor
	(*OwnerRef)(nil),                 // 5: armor.OwnerRef
	(*ListOwnerArmorsRequest)(nil),   // 6: armor.ListOwnerArmorsRequest
	(*ListOwnerArmorsResponse)(nil),  // 7: armor.ListOwnerArmorsResponse
	(*ApplyWearRequest)(nil),         // 8: armor.ApplyWearRequest
	(*ApplyWearResponse)(nil),        // 9: armor.ApplyWearResponse
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_api_proto_armor_armor_proto_depIdxs = []int32{
	4,  // 0: armor.GetArmorResponse.armor:type_name -> armor.Armor
	10, // 1: armor.Armor.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: armor.Armor.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: armor.Armor.owners:type_name -> armor.OwnerRef
	4,  // 4: armor.ListOwnerArmorsResponse.armors:type_name -> armor.Armor
	0,  // 5: armor.ArmorService.GetArmor:input_type -> armor.GetArmorRequest
	2,  // 6: armor.ArmorService.CalculateDefense:input_type -> armor.CalculateDefenseRequest
	6,  // 7: armor.ArmorService.ListOwnerArmors:input_type -> armor.ListOwnerArmorsRequest
	8,  // 8: armor.ArmorService.ApplyWear:input_type -> armor.ApplyWearRequest
	1,  // 9: armor.ArmorService.GetArmor:output_type -> armor.GetArmorResponse
	3,  // 10: armor.ArmorService.CalculateDefense:output_type -> armor.CalculateDefenseResponse
	7,  // 11: armor.ArmorService.ListOwnerArmors:output_type -> armor.ListOwnerArmorsResponse
	9,  // 12: armor.ArmorService.ApplyWear:output_type -> armor.ApplyWearResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_armor_armor_proto_init() }
func file_api_proto_armor_armor_proto_init() {
	if File_api_proto_armor_armor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_armor_armor_proto_rawDesc), len(file_api_proto_armor_armor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_armor_armor_proto_goTypes,
		DependencyIndexes: file_api_proto_armor_armor_proto_depIdxs,
		MessageInfos:      file_api_proto_armor_armor_proto_msgTypes,
	}.Build()
	File_api_proto_armor_armor_proto = out.File
	file_api_proto_armor_armor_proto_goTypes = nil
	file_api_proto_armor_armor_proto_depIdxs = nil
}
