// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/armor/armor.proto

package armor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArmorService_GetArmor_FullMethodName         = "/armor.ArmorService/GetArmor"
	ArmorService_CalculateDefense_FullMethodName = "/armor.ArmorService/CalculateDefense"
	ArmorService_ListOwnerArmors_FullMethodName  = "/armor.ArmorService/ListOwnerArmors"
	ArmorService_ApplyWear_FullMethodName        = "/armor.ArmorService/ApplyWear"
)

// ArmorServiceClient is the client API for ArmorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Armor Service (gRPC methods for service-to-service communication)
type ArmorServiceClient interface {
	// Get armor details (for other services)
	GetArmor(ctx context.Context, in *GetArmorRequest, opts ...grpc.CallOption) (*GetArmorResponse, error)
	// Calculate entity's total defense based on owned armors
	CalculateDefense(ctx context.Context, in *CalculateDefenseRequest, opts ...grpc.CallOption) (*CalculateDefenseResponse, error)
	// List armors by owner (supports warrior, enemy, dragon)
	ListOwnerArmors(ctx context.Context, in *ListOwnerArmorsRequest, opts ...grpc.CallOption) (*ListOwnerArmorsResponse, error)
	// Apply wear/damage to an armor; may mark as broken when durability reaches 0
	ApplyWear(ctx context.Context, in *ApplyWearRequest, opts ...grpc.CallOption) (*ApplyWearResponse, error)
}

type armorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArmorServiceClient(cc grpc.ClientConnInterface) ArmorServiceClient {
	return &armorServiceClient{cc}
}

func (c *armorServiceClient) GetArmor(ctx context.Context, in *GetArmorRequest, opts ...grpc.CallOption) (*GetArmorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArmorResponse)
	err := c.cc.Invoke(ctx, ArmorService_GetArmor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armorServiceClient) CalculateDefense(ctx context.Context, in *CalculateDefenseRequest, opts ...grpc.CallOption) (*CalculateDefenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDefenseResponse)
	err := c.cc.Invoke(ctx, ArmorService_CalculateDefense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armorServiceClient) ListOwnerArmors(ctx context.Context, in *ListOwnerArmorsRequest, opts ...grpc.CallOption) (*ListOwnerArmorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOwnerArmorsResponse)
	err := c.cc.Invoke(ctx, ArmorService_ListOwnerArmors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armorServiceClient) ApplyWear(ctx context.Context, in *ApplyWearRequest, opts ...grpc.CallOption) (*ApplyWearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyWearResponse)
	err := c.cc.Invoke(ctx, ArmorService_ApplyWear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArmorServiceServer is the server API for ArmorService service.
// All implementations must embed UnimplementedArmorServiceServer
// for forward compatibility.
//
// Armor Service (gRPC methods for service-to-service communication)
type ArmorServiceServer interface {
	// Get armor details (for other services)
	GetArmor(context.Context, *GetArmorRequest) (*GetArmorResponse, error)
	// Calculate entity's total defense based on owned armors
	CalculateDefense(context.Context, *CalculateDefenseRequest) (*CalculateDefenseResponse, error)
	// List armors by owner (supports warrior, enemy, dragon)
	ListOwnerArmors(context.Context, *ListOwnerArmorsRequest) (*ListOwnerArmorsResponse, error)
	// Apply wear/damage to an armor; may mark as broken when durability reaches 0
	ApplyWear(context.Context, *ApplyWearRequest) (*ApplyWearResponse, error)
	mustEmbedUnimplementedArmorServiceServer()
}

// UnimplementedArmorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArmorServiceServer struct{}

func (UnimplementedArmorServiceServer) GetArmor(context.Context, *GetArmorRequest) (*GetArmorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArmor not implemented")
}
func (UnimplementedArmorServiceServer) CalculateDefense(context.Context, *CalculateDefenseRequest) (*CalculateDefenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDefense not implemented")
}
func (UnimplementedArmorServiceServer) ListOwnerArmors(context.Context, *ListOwnerArmorsRequest) (*ListOwnerArmorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOwnerArmors not implemented")
}
func (UnimplementedArmorServiceServer) ApplyWear(context.Context, *ApplyWearRequest) (*ApplyWearResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyWear not implemented")
}
func (UnimplementedArmorServiceServer) mustEmbedUnimplementedArmorServiceServer() {}
func (UnimplementedArmorServiceServer) testEmbeddedByValue()                      {}

// UnsafeArmorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArmorServiceServer will
// result in compilation errors.
type UnsafeArmorServiceServer interface {
	mustEmbedUnimplementedArmorServiceServer()
}

func RegisterArmorServiceServer(s grpc.ServiceRegistrar, srv ArmorServiceServer) {
	// If the following call pancis, it indicates UnimplementedArmorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArmorService_ServiceDesc, srv)
}

func _ArmorService_GetArmor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArmorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmorServiceServer).GetArmor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmorService_GetArmor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmorServiceServer).GetArmor(ctx, req.(*GetArmorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmorService_CalculateDefense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDefenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmorServiceServer).CalculateDefense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmorService_CalculateDefense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmorServiceServer).CalculateDefense(ctx, req.(*CalculateDefenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmorService_ListOwnerArmors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOwnerArmorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmorServiceServer).ListOwnerArmors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmorService_ListOwnerArmors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmorServiceServer).ListOwnerArmors(ctx, req.(*ListOwnerArmorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmorService_ApplyWear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmorServiceServer).ApplyWear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmorService_ApplyWear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmorServiceServer).ApplyWear(ctx, req.(*ApplyWearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArmorService_ServiceDesc is the grpc.ServiceDesc for ArmorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArmorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "armor.ArmorService",
	HandlerType: (*ArmorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArmor",
			Handler:    _ArmorService_GetArmor_Handler,
		},
		{
			MethodName: "CalculateDefense",
			Handler:    _ArmorService_CalculateDefense_Handler,
		},
		{
			MethodName: "ListOwnerArmors",
			Handler:    _ArmorService_ListOwnerArmors_Handler,
		},
		{
			MethodName: "ApplyWear",
			Handler:    _ArmorService_ApplyWear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/armor/armor.proto",
}
