repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

namespace: network-sec

releases:
  - name: postgres
    namespace: network-sec
    chart: bitnami/postgresql
    version: 15.5.22
    values:
      - auth:
          username: postgres
          password: postgres
          database: warrior_db
        primary:
          persistence:
            enabled: true
            size: 1Gi

  - name: mysql
    namespace: network-sec
    chart: bitnami/mysql
    version: 9.19.1
    values:
      - auth:
          rootPassword: password
          username: coin_user
          password: coin_password
          database: coin_db
        primary:
          persistence:
            enabled: true
            size: 1Gi

  - name: mongodb
    namespace: network-sec
    chart: bitnami/mongodb
    version: 15.6.7
    values:
      - auth:
          enabled: false
        persistence:
          enabled: true
          size: 1Gi

  - name: kafka
    namespace: network-sec
    chart: bitnami/kafka
    version: 26.9.1
    values:
      - zookeeper:
          enabled: true
        listeners:
          client:
            protocol: PLAINTEXT
        persistence:
          enabled: false

  - name: redis
    namespace: network-sec
    chart: bitnami/redis
    version: 18.8.2
    values:
      - architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: false


