// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/weapon/weapon.proto

package weapon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get weapon
type GetWeaponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeaponId      string                 `protobuf:"bytes,1,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeaponRequest) Reset() {
	*x = GetWeaponRequest{}
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponRequest) ProtoMessage() {}

func (x *GetWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponRequest.ProtoReflect.Descriptor instead.
func (*GetWeaponRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_weapon_weapon_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeaponRequest) GetWeaponId() string {
	if x != nil {
		return x.WeaponId
	}
	return ""
}

// Response with weapon details
type GetWeaponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapon        *Weapon                `protobuf:"bytes,1,opt,name=weapon,proto3" json:"weapon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeaponResponse) Reset() {
	*x = GetWeaponResponse{}
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeaponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponResponse) ProtoMessage() {}

func (x *GetWeaponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponResponse.ProtoReflect.Descriptor instead.
func (*GetWeaponResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_weapon_weapon_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeaponResponse) GetWeapon() *Weapon {
	if x != nil {
		return x.Weapon
	}
	return nil
}

// Request to calculate power
type CalculateWarriorPowerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WarriorUsername string                 `protobuf:"bytes,1,opt,name=warrior_username,json=warriorUsername,proto3" json:"warrior_username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateWarriorPowerRequest) Reset() {
	*x = CalculateWarriorPowerRequest{}
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateWarriorPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateWarriorPowerRequest) ProtoMessage() {}

func (x *CalculateWarriorPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateWarriorPowerRequest.ProtoReflect.Descriptor instead.
func (*CalculateWarriorPowerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_weapon_weapon_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateWarriorPowerRequest) GetWarriorUsername() string {
	if x != nil {
		return x.WarriorUsername
	}
	return ""
}

// Response with calculated power
type CalculateWarriorPowerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WarriorUsername string                 `protobuf:"bytes,1,opt,name=warrior_username,json=warriorUsername,proto3" json:"warrior_username,omitempty"`
	BasePower       int32                  `protobuf:"varint,2,opt,name=base_power,json=basePower,proto3" json:"base_power,omitempty"`
	WeaponBonus     int32                  `protobuf:"varint,3,opt,name=weapon_bonus,json=weaponBonus,proto3" json:"weapon_bonus,omitempty"`
	TotalPower      int32                  `protobuf:"varint,4,opt,name=total_power,json=totalPower,proto3" json:"total_power,omitempty"`
	WeaponCount     int32                  `protobuf:"varint,5,opt,name=weapon_count,json=weaponCount,proto3" json:"weapon_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateWarriorPowerResponse) Reset() {
	*x = CalculateWarriorPowerResponse{}
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateWarriorPowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateWarriorPowerResponse) ProtoMessage() {}

func (x *CalculateWarriorPowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateWarriorPowerResponse.ProtoReflect.Descriptor instead.
func (*CalculateWarriorPowerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_weapon_weapon_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateWarriorPowerResponse) GetWarriorUsername() string {
	if x != nil {
		return x.WarriorUsername
	}
	return ""
}

func (x *CalculateWarriorPowerResponse) GetBasePower() int32 {
	if x != nil {
		return x.BasePower
	}
	return 0
}

func (x *CalculateWarriorPowerResponse) GetWeaponBonus() int32 {
	if x != nil {
		return x.WeaponBonus
	}
	return 0
}

func (x *CalculateWarriorPowerResponse) GetTotalPower() int32 {
	if x != nil {
		return x.TotalPower
	}
	return 0
}

func (x *CalculateWarriorPowerResponse) GetWeaponCount() int32 {
	if x != nil {
		return x.WeaponCount
	}
	return 0
}

// Weapon model
type Weapon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "common", "rare", "legendary"
	Damage        int32                  `protobuf:"varint,5,opt,name=damage,proto3" json:"damage,omitempty"`
	Price         int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	OwnedBy       []string               `protobuf:"bytes,8,rep,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weapon_weapon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_api_proto_weapon_weapon_proto_rawDescGZIP(), []int{4}
}

func (x *Weapon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Weapon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Weapon) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Weapon) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Weapon) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Weapon) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Weapon) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Weapon) GetOwnedBy() []string {
	if x != nil {
		return x.OwnedBy
	}
	return nil
}

func (x *Weapon) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Weapon) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_proto_weapon_weapon_proto protoreflect.FileDescriptor

const file_api_proto_weapon_weapon_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/weapon/weapon.proto\x12\x06weapon\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x10GetWeaponRequest\x12\x1b\n" +
	"\tweapon_id\x18\x01 \x01(\tR\bweaponId\";\n" +
	"\x11GetWeaponResponse\x12&\n" +
	"\x06weapon\x18\x01 \x01(\v2\x0e.weapon.WeaponR\x06weapon\"I\n" +
	"\x1cCalculateWarriorPowerRequest\x12)\n" +
	"\x10warrior_username\x18\x01 \x01(\tR\x0fwarriorUsername\"\xd0\x01\n" +
	"\x1dCalculateWarriorPowerResponse\x12)\n" +
	"\x10warrior_username\x18\x01 \x01(\tR\x0fwarriorUsername\x12\x1d\n" +
	"\n" +
	"base_power\x18\x02 \x01(\x05R\tbasePower\x12!\n" +
	"\fweapon_bonus\x18\x03 \x01(\x05R\vweaponBonus\x12\x1f\n" +
	"\vtotal_power\x18\x04 \x01(\x05R\n" +
	"totalPower\x12!\n" +
	"\fweapon_count\x18\x05 \x01(\x05R\vweaponCount\"\xc0\x02\n" +
	"\x06Weapon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06damage\x18\x05 \x01(\x05R\x06damage\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x12\x19\n" +
	"\bowned_by\x18\b \x03(\tR\aownedBy\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xb7\x01\n" +
	"\rWeaponService\x12@\n" +
	"\tGetWeapon\x12\x18.weapon.GetWeaponRequest\x1a\x19.weapon.GetWeaponResponse\x12d\n" +
	"\x15CalculateWarriorPower\x12$.weapon.CalculateWarriorPowerRequest\x1a%.weapon.CalculateWarriorPowerResponseB$Z\"network-sec-micro/api/proto/weaponb\x06proto3"

var (
	file_api_proto_weapon_weapon_proto_rawDescOnce sync.Once
	file_api_proto_weapon_weapon_proto_rawDescData []byte
)

func file_api_proto_weapon_weapon_proto_rawDescGZIP() []byte {
	file_api_proto_weapon_weapon_proto_rawDescOnce.Do(func() {
		file_api_proto_weapon_weapon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_weapon_weapon_proto_rawDesc), len(file_api_proto_weapon_weapon_proto_rawDesc)))
	})
	return file_api_proto_weapon_weapon_proto_rawDescData
}

var file_api_proto_weapon_weapon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_weapon_weapon_proto_goTypes = []any{
	(*GetWeaponRequest)(nil),              // 0: weapon.GetWeaponRequest
	(*GetWeaponResponse)(nil),             // 1: weapon.GetWeaponResponse
	(*CalculateWarriorPowerRequest)(nil),  // 2: weapon.CalculateWarriorPowerRequest
	(*CalculateWarriorPowerResponse)(nil), // 3: weapon.CalculateWarriorPowerResponse
	(*Weapon)(nil),                        // 4: weapon.Weapon
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
}
var file_api_proto_weapon_weapon_proto_depIdxs = []int32{
	4, // 0: weapon.GetWeaponResponse.weapon:type_name -> weapon.Weapon
	5, // 1: weapon.Weapon.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: weapon.Weapon.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: weapon.WeaponService.GetWeapon:input_type -> weapon.GetWeaponRequest
	2, // 4: weapon.WeaponService.CalculateWarriorPower:input_type -> weapon.CalculateWarriorPowerRequest
	1, // 5: weapon.WeaponService.GetWeapon:output_type -> weapon.GetWeaponResponse
	3, // 6: weapon.WeaponService.CalculateWarriorPower:output_type -> weapon.CalculateWarriorPowerResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_weapon_weapon_proto_init() }
func file_api_proto_weapon_weapon_proto_init() {
	if File_api_proto_weapon_weapon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_weapon_weapon_proto_rawDesc), len(file_api_proto_weapon_weapon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_weapon_weapon_proto_goTypes,
		DependencyIndexes: file_api_proto_weapon_weapon_proto_depIdxs,
		MessageInfos:      file_api_proto_weapon_weapon_proto_msgTypes,
	}.Build()
	File_api_proto_weapon_weapon_proto = out.File
	file_api_proto_weapon_weapon_proto_goTypes = nil
	file_api_proto_weapon_weapon_proto_depIdxs = nil
}
