// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/enemy/enemy.proto

package enemy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enemy represents an enemy entity
type Enemy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // Enemy ID (ObjectID hex)
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                              // Enemy name
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                              // Enemy type (goblin, pirate, skeleton, dragon)
	Level               int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                                           // Enemy level
	Health              int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`                                                         // Current HP
	MaxHealth           int32                  `protobuf:"varint,6,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`                                  // Maximum HP
	AttackPower         int32                  `protobuf:"varint,7,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`                            // Attack power
	CoinBalance         int64                  `protobuf:"varint,8,opt,name=coin_balance,json=coinBalance,proto3" json:"coin_balance,omitempty"`                            // Enemy's coin balance
	CreatedBy           string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`                                   // Creator username (dark emperor/king)
	IsHealing           bool                   `protobuf:"varint,10,opt,name=is_healing,json=isHealing,proto3" json:"is_healing,omitempty"`                                 // Is currently healing
	HealingUntilSeconds int64                  `protobuf:"varint,11,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // Unix timestamp when healing completes (0 if not healing)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Enemy) Reset() {
	*x = Enemy{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enemy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enemy) ProtoMessage() {}

func (x *Enemy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enemy.ProtoReflect.Descriptor instead.
func (*Enemy) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{0}
}

func (x *Enemy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enemy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enemy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Enemy) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Enemy) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Enemy) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *Enemy) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *Enemy) GetCoinBalance() int64 {
	if x != nil {
		return x.CoinBalance
	}
	return 0
}

func (x *Enemy) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Enemy) GetIsHealing() bool {
	if x != nil {
		return x.IsHealing
	}
	return false
}

func (x *Enemy) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

// GetEnemyByIDRequest requests an enemy by ID
type GetEnemyByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnemyId       string                 `protobuf:"bytes,1,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnemyByIDRequest) Reset() {
	*x = GetEnemyByIDRequest{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnemyByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemyByIDRequest) ProtoMessage() {}

func (x *GetEnemyByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemyByIDRequest.ProtoReflect.Descriptor instead.
func (*GetEnemyByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{1}
}

func (x *GetEnemyByIDRequest) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

// GetEnemyByIDResponse returns enemy information
type GetEnemyByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enemy         *Enemy                 `protobuf:"bytes,1,opt,name=enemy,proto3" json:"enemy,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnemyByIDResponse) Reset() {
	*x = GetEnemyByIDResponse{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnemyByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemyByIDResponse) ProtoMessage() {}

func (x *GetEnemyByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemyByIDResponse.ProtoReflect.Descriptor instead.
func (*GetEnemyByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnemyByIDResponse) GetEnemy() *Enemy {
	if x != nil {
		return x.Enemy
	}
	return nil
}

func (x *GetEnemyByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEnemyByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateEnemyHPRequest updates enemy HP
type UpdateEnemyHPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnemyId       string                 `protobuf:"bytes,1,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	NewHp         int32                  `protobuf:"varint,2,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnemyHPRequest) Reset() {
	*x = UpdateEnemyHPRequest{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnemyHPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnemyHPRequest) ProtoMessage() {}

func (x *UpdateEnemyHPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnemyHPRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnemyHPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEnemyHPRequest) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

func (x *UpdateEnemyHPRequest) GetNewHp() int32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

// UpdateEnemyHPResponse confirms HP update
type UpdateEnemyHPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,3,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnemyHPResponse) Reset() {
	*x = UpdateEnemyHPResponse{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnemyHPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnemyHPResponse) ProtoMessage() {}

func (x *UpdateEnemyHPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnemyHPResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnemyHPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEnemyHPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEnemyHPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateEnemyHPResponse) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

// UpdateEnemyHealingStateRequest sets enemy healing state
type UpdateEnemyHealingStateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnemyId             string                 `protobuf:"bytes,1,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	IsHealing           bool                   `protobuf:"varint,2,opt,name=is_healing,json=isHealing,proto3" json:"is_healing,omitempty"`
	HealingUntilSeconds int64                  `protobuf:"varint,3,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // Unix timestamp (0 if not healing)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateEnemyHealingStateRequest) Reset() {
	*x = UpdateEnemyHealingStateRequest{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnemyHealingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnemyHealingStateRequest) ProtoMessage() {}

func (x *UpdateEnemyHealingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnemyHealingStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnemyHealingStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEnemyHealingStateRequest) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

func (x *UpdateEnemyHealingStateRequest) GetIsHealing() bool {
	if x != nil {
		return x.IsHealing
	}
	return false
}

func (x *UpdateEnemyHealingStateRequest) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

// UpdateEnemyHealingStateResponse confirms healing state update
type UpdateEnemyHealingStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnemyHealingStateResponse) Reset() {
	*x = UpdateEnemyHealingStateResponse{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnemyHealingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnemyHealingStateResponse) ProtoMessage() {}

func (x *UpdateEnemyHealingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnemyHealingStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnemyHealingStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEnemyHealingStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEnemyHealingStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CheckEnemyCanBattleRequest checks if enemy can battle
type CheckEnemyCanBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnemyId       string                 `protobuf:"bytes,1,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEnemyCanBattleRequest) Reset() {
	*x = CheckEnemyCanBattleRequest{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEnemyCanBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEnemyCanBattleRequest) ProtoMessage() {}

func (x *CheckEnemyCanBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEnemyCanBattleRequest.ProtoReflect.Descriptor instead.
func (*CheckEnemyCanBattleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{7}
}

func (x *CheckEnemyCanBattleRequest) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

// CheckEnemyCanBattleResponse returns battle eligibility
type CheckEnemyCanBattleResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CanBattle           bool                   `protobuf:"varint,1,opt,name=can_battle,json=canBattle,proto3" json:"can_battle,omitempty"`
	Reason              string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                                         // Empty if can_battle is true
	HealingUntilSeconds int64                  `protobuf:"varint,3,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // If healing, when it completes
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckEnemyCanBattleResponse) Reset() {
	*x = CheckEnemyCanBattleResponse{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEnemyCanBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEnemyCanBattleResponse) ProtoMessage() {}

func (x *CheckEnemyCanBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEnemyCanBattleResponse.ProtoReflect.Descriptor instead.
func (*CheckEnemyCanBattleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{8}
}

func (x *CheckEnemyCanBattleResponse) GetCanBattle() bool {
	if x != nil {
		return x.CanBattle
	}
	return false
}

func (x *CheckEnemyCanBattleResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckEnemyCanBattleResponse) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

// DeductEnemyCoinsRequest deducts coins from enemy
type DeductEnemyCoinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnemyId       string                 `protobuf:"bytes,1,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductEnemyCoinsRequest) Reset() {
	*x = DeductEnemyCoinsRequest{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductEnemyCoinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductEnemyCoinsRequest) ProtoMessage() {}

func (x *DeductEnemyCoinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductEnemyCoinsRequest.ProtoReflect.Descriptor instead.
func (*DeductEnemyCoinsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{9}
}

func (x *DeductEnemyCoinsRequest) GetEnemyId() string {
	if x != nil {
		return x.EnemyId
	}
	return ""
}

func (x *DeductEnemyCoinsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DeductEnemyCoinsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DeductEnemyCoinsResponse confirms coin deduction
type DeductEnemyCoinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BalanceBefore int64                  `protobuf:"varint,3,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductEnemyCoinsResponse) Reset() {
	*x = DeductEnemyCoinsResponse{}
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductEnemyCoinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductEnemyCoinsResponse) ProtoMessage() {}

func (x *DeductEnemyCoinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enemy_enemy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductEnemyCoinsResponse.ProtoReflect.Descriptor instead.
func (*DeductEnemyCoinsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enemy_enemy_proto_rawDescGZIP(), []int{10}
}

func (x *DeductEnemyCoinsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductEnemyCoinsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeductEnemyCoinsResponse) GetBalanceBefore() int64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *DeductEnemyCoinsResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

var File_api_proto_enemy_enemy_proto protoreflect.FileDescriptor

const file_api_proto_enemy_enemy_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/enemy/enemy.proto\x12\x05enemy\"\xc4\x02\n" +
	"\x05Enemy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\x06 \x01(\x05R\tmaxHealth\x12!\n" +
	"\fattack_power\x18\a \x01(\x05R\vattackPower\x12!\n" +
	"\fcoin_balance\x18\b \x01(\x03R\vcoinBalance\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"is_healing\x18\n" +
	" \x01(\bR\tisHealing\x122\n" +
	"\x15healing_until_seconds\x18\v \x01(\x03R\x13healingUntilSeconds\"0\n" +
	"\x13GetEnemyByIDRequest\x12\x19\n" +
	"\benemy_id\x18\x01 \x01(\tR\aenemyId\"n\n" +
	"\x14GetEnemyByIDResponse\x12\"\n" +
	"\x05enemy\x18\x01 \x01(\v2\f.enemy.EnemyR\x05enemy\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\x14UpdateEnemyHPRequest\x12\x19\n" +
	"\benemy_id\x18\x01 \x01(\tR\aenemyId\x12\x15\n" +
	"\x06new_hp\x18\x02 \x01(\x05R\x05newHp\"j\n" +
	"\x15UpdateEnemyHPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x03 \x01(\x05R\tcurrentHp\"\x8e\x01\n" +
	"\x1eUpdateEnemyHealingStateRequest\x12\x19\n" +
	"\benemy_id\x18\x01 \x01(\tR\aenemyId\x12\x1d\n" +
	"\n" +
	"is_healing\x18\x02 \x01(\bR\tisHealing\x122\n" +
	"\x15healing_until_seconds\x18\x03 \x01(\x03R\x13healingUntilSeconds\"U\n" +
	"\x1fUpdateEnemyHealingStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x1aCheckEnemyCanBattleRequest\x12\x19\n" +
	"\benemy_id\x18\x01 \x01(\tR\aenemyId\"\x88\x01\n" +
	"\x1bCheckEnemyCanBattleResponse\x12\x1d\n" +
	"\n" +
	"can_battle\x18\x01 \x01(\bR\tcanBattle\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x122\n" +
	"\x15healing_until_seconds\x18\x03 \x01(\x03R\x13healingUntilSeconds\"d\n" +
	"\x17DeductEnemyCoinsRequest\x12\x19\n" +
	"\benemy_id\x18\x01 \x01(\tR\aenemyId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9a\x01\n" +
	"\x18DeductEnemyCoinsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ebalance_before\x18\x03 \x01(\x03R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x03R\fbalanceAfter2\xc0\x03\n" +
	"\fEnemyService\x12G\n" +
	"\fGetEnemyByID\x12\x1a.enemy.GetEnemyByIDRequest\x1a\x1b.enemy.GetEnemyByIDResponse\x12J\n" +
	"\rUpdateEnemyHP\x12\x1b.enemy.UpdateEnemyHPRequest\x1a\x1c.enemy.UpdateEnemyHPResponse\x12h\n" +
	"\x17UpdateEnemyHealingState\x12%.enemy.UpdateEnemyHealingStateRequest\x1a&.enemy.UpdateEnemyHealingStateResponse\x12\\\n" +
	"\x13CheckEnemyCanBattle\x12!.enemy.CheckEnemyCanBattleRequest\x1a\".enemy.CheckEnemyCanBattleResponse\x12S\n" +
	"\x10DeductEnemyCoins\x12\x1e.enemy.DeductEnemyCoinsRequest\x1a\x1f.enemy.DeductEnemyCoinsResponseB#Z!network-sec-micro/api/proto/enemyb\x06proto3"

var (
	file_api_proto_enemy_enemy_proto_rawDescOnce sync.Once
	file_api_proto_enemy_enemy_proto_rawDescData []byte
)

func file_api_proto_enemy_enemy_proto_rawDescGZIP() []byte {
	file_api_proto_enemy_enemy_proto_rawDescOnce.Do(func() {
		file_api_proto_enemy_enemy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_enemy_enemy_proto_rawDesc), len(file_api_proto_enemy_enemy_proto_rawDesc)))
	})
	return file_api_proto_enemy_enemy_proto_rawDescData
}

var file_api_proto_enemy_enemy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_enemy_enemy_proto_goTypes = []any{
	(*Enemy)(nil),                           // 0: enemy.Enemy
	(*GetEnemyByIDRequest)(nil),             // 1: enemy.GetEnemyByIDRequest
	(*GetEnemyByIDResponse)(nil),            // 2: enemy.GetEnemyByIDResponse
	(*UpdateEnemyHPRequest)(nil),            // 3: enemy.UpdateEnemyHPRequest
	(*UpdateEnemyHPResponse)(nil),           // 4: enemy.UpdateEnemyHPResponse
	(*UpdateEnemyHealingStateRequest)(nil),  // 5: enemy.UpdateEnemyHealingStateRequest
	(*UpdateEnemyHealingStateResponse)(nil), // 6: enemy.UpdateEnemyHealingStateResponse
	(*CheckEnemyCanBattleRequest)(nil),      // 7: enemy.CheckEnemyCanBattleRequest
	(*CheckEnemyCanBattleResponse)(nil),     // 8: enemy.CheckEnemyCanBattleResponse
	(*DeductEnemyCoinsRequest)(nil),         // 9: enemy.DeductEnemyCoinsRequest
	(*DeductEnemyCoinsResponse)(nil),        // 10: enemy.DeductEnemyCoinsResponse
}
var file_api_proto_enemy_enemy_proto_depIdxs = []int32{
	0,  // 0: enemy.GetEnemyByIDResponse.enemy:type_name -> enemy.Enemy
	1,  // 1: enemy.EnemyService.GetEnemyByID:input_type -> enemy.GetEnemyByIDRequest
	3,  // 2: enemy.EnemyService.UpdateEnemyHP:input_type -> enemy.UpdateEnemyHPRequest
	5,  // 3: enemy.EnemyService.UpdateEnemyHealingState:input_type -> enemy.UpdateEnemyHealingStateRequest
	7,  // 4: enemy.EnemyService.CheckEnemyCanBattle:input_type -> enemy.CheckEnemyCanBattleRequest
	9,  // 5: enemy.EnemyService.DeductEnemyCoins:input_type -> enemy.DeductEnemyCoinsRequest
	2,  // 6: enemy.EnemyService.GetEnemyByID:output_type -> enemy.GetEnemyByIDResponse
	4,  // 7: enemy.EnemyService.UpdateEnemyHP:output_type -> enemy.UpdateEnemyHPResponse
	6,  // 8: enemy.EnemyService.UpdateEnemyHealingState:output_type -> enemy.UpdateEnemyHealingStateResponse
	8,  // 9: enemy.EnemyService.CheckEnemyCanBattle:output_type -> enemy.CheckEnemyCanBattleResponse
	10, // 10: enemy.EnemyService.DeductEnemyCoins:output_type -> enemy.DeductEnemyCoinsResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_enemy_enemy_proto_init() }
func file_api_proto_enemy_enemy_proto_init() {
	if File_api_proto_enemy_enemy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_enemy_enemy_proto_rawDesc), len(file_api_proto_enemy_enemy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_enemy_enemy_proto_goTypes,
		DependencyIndexes: file_api_proto_enemy_enemy_proto_depIdxs,
		MessageInfos:      file_api_proto_enemy_enemy_proto_msgTypes,
	}.Build()
	File_api_proto_enemy_enemy_proto = out.File
	file_api_proto_enemy_enemy_proto_goTypes = nil
	file_api_proto_enemy_enemy_proto_depIdxs = nil
}
