// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/enemy/enemy.proto

package enemy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnemyService_GetEnemyByID_FullMethodName            = "/enemy.EnemyService/GetEnemyByID"
	EnemyService_UpdateEnemyHP_FullMethodName           = "/enemy.EnemyService/UpdateEnemyHP"
	EnemyService_UpdateEnemyHealingState_FullMethodName = "/enemy.EnemyService/UpdateEnemyHealingState"
	EnemyService_CheckEnemyCanBattle_FullMethodName     = "/enemy.EnemyService/CheckEnemyCanBattle"
)

// EnemyServiceClient is the client API for EnemyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnemyService provides gRPC endpoints for enemy operations
type EnemyServiceClient interface {
	// GetEnemyByID retrieves an enemy by its ID
	GetEnemyByID(ctx context.Context, in *GetEnemyByIDRequest, opts ...grpc.CallOption) (*GetEnemyByIDResponse, error)
	// UpdateEnemyHP updates an enemy's HP
	UpdateEnemyHP(ctx context.Context, in *UpdateEnemyHPRequest, opts ...grpc.CallOption) (*UpdateEnemyHPResponse, error)
	// UpdateEnemyHealingState sets enemy's healing state (for heal service)
	UpdateEnemyHealingState(ctx context.Context, in *UpdateEnemyHealingStateRequest, opts ...grpc.CallOption) (*UpdateEnemyHealingStateResponse, error)
	// CheckEnemyCanBattle checks if an enemy can participate in battles (not healing)
	CheckEnemyCanBattle(ctx context.Context, in *CheckEnemyCanBattleRequest, opts ...grpc.CallOption) (*CheckEnemyCanBattleResponse, error)
}

type enemyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnemyServiceClient(cc grpc.ClientConnInterface) EnemyServiceClient {
	return &enemyServiceClient{cc}
}

func (c *enemyServiceClient) GetEnemyByID(ctx context.Context, in *GetEnemyByIDRequest, opts ...grpc.CallOption) (*GetEnemyByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnemyByIDResponse)
	err := c.cc.Invoke(ctx, EnemyService_GetEnemyByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enemyServiceClient) UpdateEnemyHP(ctx context.Context, in *UpdateEnemyHPRequest, opts ...grpc.CallOption) (*UpdateEnemyHPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnemyHPResponse)
	err := c.cc.Invoke(ctx, EnemyService_UpdateEnemyHP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enemyServiceClient) UpdateEnemyHealingState(ctx context.Context, in *UpdateEnemyHealingStateRequest, opts ...grpc.CallOption) (*UpdateEnemyHealingStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnemyHealingStateResponse)
	err := c.cc.Invoke(ctx, EnemyService_UpdateEnemyHealingState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enemyServiceClient) CheckEnemyCanBattle(ctx context.Context, in *CheckEnemyCanBattleRequest, opts ...grpc.CallOption) (*CheckEnemyCanBattleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEnemyCanBattleResponse)
	err := c.cc.Invoke(ctx, EnemyService_CheckEnemyCanBattle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnemyServiceServer is the server API for EnemyService service.
// All implementations must embed UnimplementedEnemyServiceServer
// for forward compatibility.
//
// EnemyService provides gRPC endpoints for enemy operations
type EnemyServiceServer interface {
	// GetEnemyByID retrieves an enemy by its ID
	GetEnemyByID(context.Context, *GetEnemyByIDRequest) (*GetEnemyByIDResponse, error)
	// UpdateEnemyHP updates an enemy's HP
	UpdateEnemyHP(context.Context, *UpdateEnemyHPRequest) (*UpdateEnemyHPResponse, error)
	// UpdateEnemyHealingState sets enemy's healing state (for heal service)
	UpdateEnemyHealingState(context.Context, *UpdateEnemyHealingStateRequest) (*UpdateEnemyHealingStateResponse, error)
	// CheckEnemyCanBattle checks if an enemy can participate in battles (not healing)
	CheckEnemyCanBattle(context.Context, *CheckEnemyCanBattleRequest) (*CheckEnemyCanBattleResponse, error)
	mustEmbedUnimplementedEnemyServiceServer()
}

// UnimplementedEnemyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnemyServiceServer struct{}

func (UnimplementedEnemyServiceServer) GetEnemyByID(context.Context, *GetEnemyByIDRequest) (*GetEnemyByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnemyByID not implemented")
}
func (UnimplementedEnemyServiceServer) UpdateEnemyHP(context.Context, *UpdateEnemyHPRequest) (*UpdateEnemyHPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnemyHP not implemented")
}
func (UnimplementedEnemyServiceServer) UpdateEnemyHealingState(context.Context, *UpdateEnemyHealingStateRequest) (*UpdateEnemyHealingStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnemyHealingState not implemented")
}
func (UnimplementedEnemyServiceServer) CheckEnemyCanBattle(context.Context, *CheckEnemyCanBattleRequest) (*CheckEnemyCanBattleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEnemyCanBattle not implemented")
}
func (UnimplementedEnemyServiceServer) mustEmbedUnimplementedEnemyServiceServer() {}
func (UnimplementedEnemyServiceServer) testEmbeddedByValue()                      {}

// UnsafeEnemyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnemyServiceServer will
// result in compilation errors.
type UnsafeEnemyServiceServer interface {
	mustEmbedUnimplementedEnemyServiceServer()
}

func RegisterEnemyServiceServer(s grpc.ServiceRegistrar, srv EnemyServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnemyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnemyService_ServiceDesc, srv)
}

func _EnemyService_GetEnemyByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnemyByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnemyServiceServer).GetEnemyByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnemyService_GetEnemyByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnemyServiceServer).GetEnemyByID(ctx, req.(*GetEnemyByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnemyService_UpdateEnemyHP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnemyHPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnemyServiceServer).UpdateEnemyHP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnemyService_UpdateEnemyHP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnemyServiceServer).UpdateEnemyHP(ctx, req.(*UpdateEnemyHPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnemyService_UpdateEnemyHealingState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnemyHealingStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnemyServiceServer).UpdateEnemyHealingState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnemyService_UpdateEnemyHealingState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnemyServiceServer).UpdateEnemyHealingState(ctx, req.(*UpdateEnemyHealingStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnemyService_CheckEnemyCanBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEnemyCanBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnemyServiceServer).CheckEnemyCanBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnemyService_CheckEnemyCanBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnemyServiceServer).CheckEnemyCanBattle(ctx, req.(*CheckEnemyCanBattleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnemyService_ServiceDesc is the grpc.ServiceDesc for EnemyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnemyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enemy.EnemyService",
	HandlerType: (*EnemyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnemyByID",
			Handler:    _EnemyService_GetEnemyByID_Handler,
		},
		{
			MethodName: "UpdateEnemyHP",
			Handler:    _EnemyService_UpdateEnemyHP_Handler,
		},
		{
			MethodName: "UpdateEnemyHealingState",
			Handler:    _EnemyService_UpdateEnemyHealingState_Handler,
		},
		{
			MethodName: "CheckEnemyCanBattle",
			Handler:    _EnemyService_CheckEnemyCanBattle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/enemy/enemy.proto",
}
