// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/dragon/dragon.proto

package dragon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DragonService_GetDragonByID_FullMethodName            = "/dragon.DragonService/GetDragonByID"
	DragonService_UpdateDragonHP_FullMethodName           = "/dragon.DragonService/UpdateDragonHP"
	DragonService_UpdateDragonHealingState_FullMethodName = "/dragon.DragonService/UpdateDragonHealingState"
	DragonService_CheckDragonCanBattle_FullMethodName     = "/dragon.DragonService/CheckDragonCanBattle"
)

// DragonServiceClient is the client API for DragonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DragonService provides gRPC endpoints for dragon operations
type DragonServiceClient interface {
	// GetDragonByID retrieves a dragon by its ID
	GetDragonByID(ctx context.Context, in *GetDragonByIDRequest, opts ...grpc.CallOption) (*GetDragonByIDResponse, error)
	// UpdateDragonHP updates a dragon's HP
	UpdateDragonHP(ctx context.Context, in *UpdateDragonHPRequest, opts ...grpc.CallOption) (*UpdateDragonHPResponse, error)
	// UpdateDragonHealingState sets dragon's healing state (for heal service)
	UpdateDragonHealingState(ctx context.Context, in *UpdateDragonHealingStateRequest, opts ...grpc.CallOption) (*UpdateDragonHealingStateResponse, error)
	// CheckDragonCanBattle checks if a dragon can participate in battles (not healing)
	CheckDragonCanBattle(ctx context.Context, in *CheckDragonCanBattleRequest, opts ...grpc.CallOption) (*CheckDragonCanBattleResponse, error)
}

type dragonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDragonServiceClient(cc grpc.ClientConnInterface) DragonServiceClient {
	return &dragonServiceClient{cc}
}

func (c *dragonServiceClient) GetDragonByID(ctx context.Context, in *GetDragonByIDRequest, opts ...grpc.CallOption) (*GetDragonByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDragonByIDResponse)
	err := c.cc.Invoke(ctx, DragonService_GetDragonByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonServiceClient) UpdateDragonHP(ctx context.Context, in *UpdateDragonHPRequest, opts ...grpc.CallOption) (*UpdateDragonHPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDragonHPResponse)
	err := c.cc.Invoke(ctx, DragonService_UpdateDragonHP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonServiceClient) UpdateDragonHealingState(ctx context.Context, in *UpdateDragonHealingStateRequest, opts ...grpc.CallOption) (*UpdateDragonHealingStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDragonHealingStateResponse)
	err := c.cc.Invoke(ctx, DragonService_UpdateDragonHealingState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonServiceClient) CheckDragonCanBattle(ctx context.Context, in *CheckDragonCanBattleRequest, opts ...grpc.CallOption) (*CheckDragonCanBattleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckDragonCanBattleResponse)
	err := c.cc.Invoke(ctx, DragonService_CheckDragonCanBattle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DragonServiceServer is the server API for DragonService service.
// All implementations must embed UnimplementedDragonServiceServer
// for forward compatibility.
//
// DragonService provides gRPC endpoints for dragon operations
type DragonServiceServer interface {
	// GetDragonByID retrieves a dragon by its ID
	GetDragonByID(context.Context, *GetDragonByIDRequest) (*GetDragonByIDResponse, error)
	// UpdateDragonHP updates a dragon's HP
	UpdateDragonHP(context.Context, *UpdateDragonHPRequest) (*UpdateDragonHPResponse, error)
	// UpdateDragonHealingState sets dragon's healing state (for heal service)
	UpdateDragonHealingState(context.Context, *UpdateDragonHealingStateRequest) (*UpdateDragonHealingStateResponse, error)
	// CheckDragonCanBattle checks if a dragon can participate in battles (not healing)
	CheckDragonCanBattle(context.Context, *CheckDragonCanBattleRequest) (*CheckDragonCanBattleResponse, error)
	mustEmbedUnimplementedDragonServiceServer()
}

// UnimplementedDragonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDragonServiceServer struct{}

func (UnimplementedDragonServiceServer) GetDragonByID(context.Context, *GetDragonByIDRequest) (*GetDragonByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDragonByID not implemented")
}
func (UnimplementedDragonServiceServer) UpdateDragonHP(context.Context, *UpdateDragonHPRequest) (*UpdateDragonHPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDragonHP not implemented")
}
func (UnimplementedDragonServiceServer) UpdateDragonHealingState(context.Context, *UpdateDragonHealingStateRequest) (*UpdateDragonHealingStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDragonHealingState not implemented")
}
func (UnimplementedDragonServiceServer) CheckDragonCanBattle(context.Context, *CheckDragonCanBattleRequest) (*CheckDragonCanBattleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDragonCanBattle not implemented")
}
func (UnimplementedDragonServiceServer) mustEmbedUnimplementedDragonServiceServer() {}
func (UnimplementedDragonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDragonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DragonServiceServer will
// result in compilation errors.
type UnsafeDragonServiceServer interface {
	mustEmbedUnimplementedDragonServiceServer()
}

func RegisterDragonServiceServer(s grpc.ServiceRegistrar, srv DragonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDragonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DragonService_ServiceDesc, srv)
}

func _DragonService_GetDragonByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDragonByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonServiceServer).GetDragonByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonService_GetDragonByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonServiceServer).GetDragonByID(ctx, req.(*GetDragonByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonService_UpdateDragonHP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDragonHPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonServiceServer).UpdateDragonHP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonService_UpdateDragonHP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonServiceServer).UpdateDragonHP(ctx, req.(*UpdateDragonHPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonService_UpdateDragonHealingState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDragonHealingStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonServiceServer).UpdateDragonHealingState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonService_UpdateDragonHealingState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonServiceServer).UpdateDragonHealingState(ctx, req.(*UpdateDragonHealingStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonService_CheckDragonCanBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDragonCanBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonServiceServer).CheckDragonCanBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonService_CheckDragonCanBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonServiceServer).CheckDragonCanBattle(ctx, req.(*CheckDragonCanBattleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DragonService_ServiceDesc is the grpc.ServiceDesc for DragonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DragonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dragon.DragonService",
	HandlerType: (*DragonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDragonByID",
			Handler:    _DragonService_GetDragonByID_Handler,
		},
		{
			MethodName: "UpdateDragonHP",
			Handler:    _DragonService_UpdateDragonHP_Handler,
		},
		{
			MethodName: "UpdateDragonHealingState",
			Handler:    _DragonService_UpdateDragonHealingState_Handler,
		},
		{
			MethodName: "CheckDragonCanBattle",
			Handler:    _DragonService_CheckDragonCanBattle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/dragon/dragon.proto",
}
