// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/dragon/dragon.proto

package dragon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dragon represents a dragon entity
type Dragon struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // Dragon ID (ObjectID hex)
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                              // Dragon name
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                              // Dragon type (fire, ice, lightning, shadow)
	Level               int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                                           // Dragon level
	Health              int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`                                                         // Current HP
	MaxHealth           int32                  `protobuf:"varint,6,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`                                  // Maximum HP
	AttackPower         int32                  `protobuf:"varint,7,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`                            // Attack power
	Defense             int32                  `protobuf:"varint,8,opt,name=defense,proto3" json:"defense,omitempty"`                                                       // Defense
	CreatedBy           string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`                                   // Creator username (dark emperor)
	IsAlive             bool                   `protobuf:"varint,10,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`                                       // Is dragon alive
	IsHealing           bool                   `protobuf:"varint,11,opt,name=is_healing,json=isHealing,proto3" json:"is_healing,omitempty"`                                 // Is currently healing
	HealingUntilSeconds int64                  `protobuf:"varint,12,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // Unix timestamp when healing completes (0 if not healing)
	RevivalCount        int32                  `protobuf:"varint,13,opt,name=revival_count,json=revivalCount,proto3" json:"revival_count,omitempty"`                        // Number of times revived (max 3)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Dragon) Reset() {
	*x = Dragon{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dragon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dragon) ProtoMessage() {}

func (x *Dragon) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dragon.ProtoReflect.Descriptor instead.
func (*Dragon) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{0}
}

func (x *Dragon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dragon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dragon) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dragon) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Dragon) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Dragon) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *Dragon) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *Dragon) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *Dragon) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Dragon) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Dragon) GetIsHealing() bool {
	if x != nil {
		return x.IsHealing
	}
	return false
}

func (x *Dragon) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

func (x *Dragon) GetRevivalCount() int32 {
	if x != nil {
		return x.RevivalCount
	}
	return 0
}

// GetDragonByIDRequest requests a dragon by ID
type GetDragonByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DragonId      string                 `protobuf:"bytes,1,opt,name=dragon_id,json=dragonId,proto3" json:"dragon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDragonByIDRequest) Reset() {
	*x = GetDragonByIDRequest{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDragonByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDragonByIDRequest) ProtoMessage() {}

func (x *GetDragonByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDragonByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDragonByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{1}
}

func (x *GetDragonByIDRequest) GetDragonId() string {
	if x != nil {
		return x.DragonId
	}
	return ""
}

// GetDragonByIDResponse returns dragon information
type GetDragonByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dragon        *Dragon                `protobuf:"bytes,1,opt,name=dragon,proto3" json:"dragon,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDragonByIDResponse) Reset() {
	*x = GetDragonByIDResponse{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDragonByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDragonByIDResponse) ProtoMessage() {}

func (x *GetDragonByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDragonByIDResponse.ProtoReflect.Descriptor instead.
func (*GetDragonByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{2}
}

func (x *GetDragonByIDResponse) GetDragon() *Dragon {
	if x != nil {
		return x.Dragon
	}
	return nil
}

func (x *GetDragonByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDragonByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateDragonHPRequest updates dragon HP
type UpdateDragonHPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DragonId      string                 `protobuf:"bytes,1,opt,name=dragon_id,json=dragonId,proto3" json:"dragon_id,omitempty"`
	NewHp         int32                  `protobuf:"varint,2,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDragonHPRequest) Reset() {
	*x = UpdateDragonHPRequest{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDragonHPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDragonHPRequest) ProtoMessage() {}

func (x *UpdateDragonHPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDragonHPRequest.ProtoReflect.Descriptor instead.
func (*UpdateDragonHPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDragonHPRequest) GetDragonId() string {
	if x != nil {
		return x.DragonId
	}
	return ""
}

func (x *UpdateDragonHPRequest) GetNewHp() int32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

// UpdateDragonHPResponse confirms HP update
type UpdateDragonHPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,3,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDragonHPResponse) Reset() {
	*x = UpdateDragonHPResponse{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDragonHPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDragonHPResponse) ProtoMessage() {}

func (x *UpdateDragonHPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDragonHPResponse.ProtoReflect.Descriptor instead.
func (*UpdateDragonHPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDragonHPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDragonHPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDragonHPResponse) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

// UpdateDragonHealingStateRequest sets dragon healing state
type UpdateDragonHealingStateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DragonId            string                 `protobuf:"bytes,1,opt,name=dragon_id,json=dragonId,proto3" json:"dragon_id,omitempty"`
	IsHealing           bool                   `protobuf:"varint,2,opt,name=is_healing,json=isHealing,proto3" json:"is_healing,omitempty"`
	HealingUntilSeconds int64                  `protobuf:"varint,3,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // Unix timestamp (0 if not healing)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateDragonHealingStateRequest) Reset() {
	*x = UpdateDragonHealingStateRequest{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDragonHealingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDragonHealingStateRequest) ProtoMessage() {}

func (x *UpdateDragonHealingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDragonHealingStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateDragonHealingStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDragonHealingStateRequest) GetDragonId() string {
	if x != nil {
		return x.DragonId
	}
	return ""
}

func (x *UpdateDragonHealingStateRequest) GetIsHealing() bool {
	if x != nil {
		return x.IsHealing
	}
	return false
}

func (x *UpdateDragonHealingStateRequest) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

// UpdateDragonHealingStateResponse confirms healing state update
type UpdateDragonHealingStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDragonHealingStateResponse) Reset() {
	*x = UpdateDragonHealingStateResponse{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDragonHealingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDragonHealingStateResponse) ProtoMessage() {}

func (x *UpdateDragonHealingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDragonHealingStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateDragonHealingStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDragonHealingStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDragonHealingStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CheckDragonCanBattleRequest checks if dragon can battle
type CheckDragonCanBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DragonId      string                 `protobuf:"bytes,1,opt,name=dragon_id,json=dragonId,proto3" json:"dragon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDragonCanBattleRequest) Reset() {
	*x = CheckDragonCanBattleRequest{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDragonCanBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDragonCanBattleRequest) ProtoMessage() {}

func (x *CheckDragonCanBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDragonCanBattleRequest.ProtoReflect.Descriptor instead.
func (*CheckDragonCanBattleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{7}
}

func (x *CheckDragonCanBattleRequest) GetDragonId() string {
	if x != nil {
		return x.DragonId
	}
	return ""
}

// CheckDragonCanBattleResponse returns battle eligibility
type CheckDragonCanBattleResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CanBattle           bool                   `protobuf:"varint,1,opt,name=can_battle,json=canBattle,proto3" json:"can_battle,omitempty"`
	Reason              string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                                         // Empty if can_battle is true
	HealingUntilSeconds int64                  `protobuf:"varint,3,opt,name=healing_until_seconds,json=healingUntilSeconds,proto3" json:"healing_until_seconds,omitempty"` // If healing, when it completes
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckDragonCanBattleResponse) Reset() {
	*x = CheckDragonCanBattleResponse{}
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDragonCanBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDragonCanBattleResponse) ProtoMessage() {}

func (x *CheckDragonCanBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dragon_dragon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDragonCanBattleResponse.ProtoReflect.Descriptor instead.
func (*CheckDragonCanBattleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dragon_dragon_proto_rawDescGZIP(), []int{8}
}

func (x *CheckDragonCanBattleResponse) GetCanBattle() bool {
	if x != nil {
		return x.CanBattle
	}
	return false
}

func (x *CheckDragonCanBattleResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckDragonCanBattleResponse) GetHealingUntilSeconds() int64 {
	if x != nil {
		return x.HealingUntilSeconds
	}
	return 0
}

var File_api_proto_dragon_dragon_proto protoreflect.FileDescriptor

const file_api_proto_dragon_dragon_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/dragon/dragon.proto\x12\x06dragon\"\xfc\x02\n" +
	"\x06Dragon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\x06 \x01(\x05R\tmaxHealth\x12!\n" +
	"\fattack_power\x18\a \x01(\x05R\vattackPower\x12\x18\n" +
	"\adefense\x18\b \x01(\x05R\adefense\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x19\n" +
	"\bis_alive\x18\n" +
	" \x01(\bR\aisAlive\x12\x1d\n" +
	"\n" +
	"is_healing\x18\v \x01(\bR\tisHealing\x122\n" +
	"\x15healing_until_seconds\x18\f \x01(\x03R\x13healingUntilSeconds\x12#\n" +
	"\rrevival_count\x18\r \x01(\x05R\frevivalCount\"3\n" +
	"\x14GetDragonByIDRequest\x12\x1b\n" +
	"\tdragon_id\x18\x01 \x01(\tR\bdragonId\"s\n" +
	"\x15GetDragonByIDResponse\x12&\n" +
	"\x06dragon\x18\x01 \x01(\v2\x0e.dragon.DragonR\x06dragon\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"K\n" +
	"\x15UpdateDragonHPRequest\x12\x1b\n" +
	"\tdragon_id\x18\x01 \x01(\tR\bdragonId\x12\x15\n" +
	"\x06new_hp\x18\x02 \x01(\x05R\x05newHp\"k\n" +
	"\x16UpdateDragonHPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x03 \x01(\x05R\tcurrentHp\"\x91\x01\n" +
	"\x1fUpdateDragonHealingStateRequest\x12\x1b\n" +
	"\tdragon_id\x18\x01 \x01(\tR\bdragonId\x12\x1d\n" +
	"\n" +
	"is_healing\x18\x02 \x01(\bR\tisHealing\x122\n" +
	"\x15healing_until_seconds\x18\x03 \x01(\x03R\x13healingUntilSeconds\"V\n" +
	" UpdateDragonHealingStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x1bCheckDragonCanBattleRequest\x12\x1b\n" +
	"\tdragon_id\x18\x01 \x01(\tR\bdragonId\"\x89\x01\n" +
	"\x1cCheckDragonCanBattleResponse\x12\x1d\n" +
	"\n" +
	"can_battle\x18\x01 \x01(\bR\tcanBattle\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x122\n" +
	"\x15healing_until_seconds\x18\x03 \x01(\x03R\x13healingUntilSeconds2\x80\x03\n" +
	"\rDragonService\x12L\n" +
	"\rGetDragonByID\x12\x1c.dragon.GetDragonByIDRequest\x1a\x1d.dragon.GetDragonByIDResponse\x12O\n" +
	"\x0eUpdateDragonHP\x12\x1d.dragon.UpdateDragonHPRequest\x1a\x1e.dragon.UpdateDragonHPResponse\x12m\n" +
	"\x18UpdateDragonHealingState\x12'.dragon.UpdateDragonHealingStateRequest\x1a(.dragon.UpdateDragonHealingStateResponse\x12a\n" +
	"\x14CheckDragonCanBattle\x12#.dragon.CheckDragonCanBattleRequest\x1a$.dragon.CheckDragonCanBattleResponseB$Z\"network-sec-micro/api/proto/dragonb\x06proto3"

var (
	file_api_proto_dragon_dragon_proto_rawDescOnce sync.Once
	file_api_proto_dragon_dragon_proto_rawDescData []byte
)

func file_api_proto_dragon_dragon_proto_rawDescGZIP() []byte {
	file_api_proto_dragon_dragon_proto_rawDescOnce.Do(func() {
		file_api_proto_dragon_dragon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dragon_dragon_proto_rawDesc), len(file_api_proto_dragon_dragon_proto_rawDesc)))
	})
	return file_api_proto_dragon_dragon_proto_rawDescData
}

var file_api_proto_dragon_dragon_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_dragon_dragon_proto_goTypes = []any{
	(*Dragon)(nil),                           // 0: dragon.Dragon
	(*GetDragonByIDRequest)(nil),             // 1: dragon.GetDragonByIDRequest
	(*GetDragonByIDResponse)(nil),            // 2: dragon.GetDragonByIDResponse
	(*UpdateDragonHPRequest)(nil),            // 3: dragon.UpdateDragonHPRequest
	(*UpdateDragonHPResponse)(nil),           // 4: dragon.UpdateDragonHPResponse
	(*UpdateDragonHealingStateRequest)(nil),  // 5: dragon.UpdateDragonHealingStateRequest
	(*UpdateDragonHealingStateResponse)(nil), // 6: dragon.UpdateDragonHealingStateResponse
	(*CheckDragonCanBattleRequest)(nil),      // 7: dragon.CheckDragonCanBattleRequest
	(*CheckDragonCanBattleResponse)(nil),     // 8: dragon.CheckDragonCanBattleResponse
}
var file_api_proto_dragon_dragon_proto_depIdxs = []int32{
	0, // 0: dragon.GetDragonByIDResponse.dragon:type_name -> dragon.Dragon
	1, // 1: dragon.DragonService.GetDragonByID:input_type -> dragon.GetDragonByIDRequest
	3, // 2: dragon.DragonService.UpdateDragonHP:input_type -> dragon.UpdateDragonHPRequest
	5, // 3: dragon.DragonService.UpdateDragonHealingState:input_type -> dragon.UpdateDragonHealingStateRequest
	7, // 4: dragon.DragonService.CheckDragonCanBattle:input_type -> dragon.CheckDragonCanBattleRequest
	2, // 5: dragon.DragonService.GetDragonByID:output_type -> dragon.GetDragonByIDResponse
	4, // 6: dragon.DragonService.UpdateDragonHP:output_type -> dragon.UpdateDragonHPResponse
	6, // 7: dragon.DragonService.UpdateDragonHealingState:output_type -> dragon.UpdateDragonHealingStateResponse
	8, // 8: dragon.DragonService.CheckDragonCanBattle:output_type -> dragon.CheckDragonCanBattleResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_dragon_dragon_proto_init() }
func file_api_proto_dragon_dragon_proto_init() {
	if File_api_proto_dragon_dragon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dragon_dragon_proto_rawDesc), len(file_api_proto_dragon_dragon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dragon_dragon_proto_goTypes,
		DependencyIndexes: file_api_proto_dragon_dragon_proto_depIdxs,
		MessageInfos:      file_api_proto_dragon_dragon_proto_msgTypes,
	}.Build()
	File_api_proto_dragon_dragon_proto = out.File
	file_api_proto_dragon_dragon_proto_goTypes = nil
	file_api_proto_dragon_dragon_proto_depIdxs = nil
}
