// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
    "network-sec-micro/internal/weapon"
)

// Injectors from wire.go:

func InitializeWeaponApp() (*weapon.Service, *weapon.Handler, error) {
    service := weapon.NewService()
    handler := weapon.NewHandler(service)
    return service, handler, nil
}


