// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/heal/heal.proto

package heal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to purchase heal
type PurchaseHealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarriorId     string                 `protobuf:"bytes,1,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	HealType      string                 `protobuf:"bytes,2,opt,name=heal_type,json=healType,proto3" json:"heal_type,omitempty"` // "full" or "partial" (50%)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseHealRequest) Reset() {
	*x = PurchaseHealRequest{}
	mi := &file_api_proto_heal_heal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseHealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseHealRequest) ProtoMessage() {}

func (x *PurchaseHealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heal_heal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseHealRequest.ProtoReflect.Descriptor instead.
func (*PurchaseHealRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_heal_heal_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseHealRequest) GetWarriorId() string {
	if x != nil {
		return x.WarriorId
	}
	return ""
}

func (x *PurchaseHealRequest) GetHealType() string {
	if x != nil {
		return x.HealType
	}
	return ""
}

// Response after purchase
type PurchaseHealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HealedAmount  int32                  `protobuf:"varint,3,opt,name=healed_amount,json=healedAmount,proto3" json:"healed_amount,omitempty"`
	NewHp         int32                  `protobuf:"varint,4,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	CoinsSpent    int32                  `protobuf:"varint,5,opt,name=coins_spent,json=coinsSpent,proto3" json:"coins_spent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseHealResponse) Reset() {
	*x = PurchaseHealResponse{}
	mi := &file_api_proto_heal_heal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseHealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseHealResponse) ProtoMessage() {}

func (x *PurchaseHealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heal_heal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseHealResponse.ProtoReflect.Descriptor instead.
func (*PurchaseHealResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_heal_heal_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseHealResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurchaseHealResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PurchaseHealResponse) GetHealedAmount() int32 {
	if x != nil {
		return x.HealedAmount
	}
	return 0
}

func (x *PurchaseHealResponse) GetNewHp() int32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

func (x *PurchaseHealResponse) GetCoinsSpent() int32 {
	if x != nil {
		return x.CoinsSpent
	}
	return 0
}

// Request to get healing history
type GetHealingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarriorId     string                 `protobuf:"bytes,1,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealingHistoryRequest) Reset() {
	*x = GetHealingHistoryRequest{}
	mi := &file_api_proto_heal_heal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealingHistoryRequest) ProtoMessage() {}

func (x *GetHealingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heal_heal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHealingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_heal_heal_proto_rawDescGZIP(), []int{2}
}

func (x *GetHealingHistoryRequest) GetWarriorId() string {
	if x != nil {
		return x.WarriorId
	}
	return ""
}

// Response with healing history
type GetHealingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*HealingRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealingHistoryResponse) Reset() {
	*x = GetHealingHistoryResponse{}
	mi := &file_api_proto_heal_heal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealingHistoryResponse) ProtoMessage() {}

func (x *GetHealingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heal_heal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHealingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_heal_heal_proto_rawDescGZIP(), []int{3}
}

func (x *GetHealingHistoryResponse) GetRecords() []*HealingRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// Healing record
type HealingRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WarriorId     string                 `protobuf:"bytes,2,opt,name=warrior_id,json=warriorId,proto3" json:"warrior_id,omitempty"`
	HealType      string                 `protobuf:"bytes,3,opt,name=heal_type,json=healType,proto3" json:"heal_type,omitempty"`
	HealedAmount  int32                  `protobuf:"varint,4,opt,name=healed_amount,json=healedAmount,proto3" json:"healed_amount,omitempty"`
	CoinsSpent    int32                  `protobuf:"varint,5,opt,name=coins_spent,json=coinsSpent,proto3" json:"coins_spent,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealingRecord) Reset() {
	*x = HealingRecord{}
	mi := &file_api_proto_heal_heal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingRecord) ProtoMessage() {}

func (x *HealingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heal_heal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingRecord.ProtoReflect.Descriptor instead.
func (*HealingRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_heal_heal_proto_rawDescGZIP(), []int{4}
}

func (x *HealingRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealingRecord) GetWarriorId() string {
	if x != nil {
		return x.WarriorId
	}
	return ""
}

func (x *HealingRecord) GetHealType() string {
	if x != nil {
		return x.HealType
	}
	return ""
}

func (x *HealingRecord) GetHealedAmount() int32 {
	if x != nil {
		return x.HealedAmount
	}
	return 0
}

func (x *HealingRecord) GetCoinsSpent() int32 {
	if x != nil {
		return x.CoinsSpent
	}
	return 0
}

func (x *HealingRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_heal_heal_proto protoreflect.FileDescriptor

const file_api_proto_heal_heal_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/heal/heal.proto\x12\x04heal\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\x13PurchaseHealRequest\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x01 \x01(\tR\twarriorId\x12\x1b\n" +
	"\theal_type\x18\x02 \x01(\tR\bhealType\"\xa7\x01\n" +
	"\x14PurchaseHealResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rhealed_amount\x18\x03 \x01(\x05R\fhealedAmount\x12\x15\n" +
	"\x06new_hp\x18\x04 \x01(\x05R\x05newHp\x12\x1f\n" +
	"\vcoins_spent\x18\x05 \x01(\x05R\n" +
	"coinsSpent\"9\n" +
	"\x18GetHealingHistoryRequest\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x01 \x01(\tR\twarriorId\"J\n" +
	"\x19GetHealingHistoryResponse\x12-\n" +
	"\arecords\x18\x01 \x03(\v2\x13.heal.HealingRecordR\arecords\"\xdc\x01\n" +
	"\rHealingRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"warrior_id\x18\x02 \x01(\tR\twarriorId\x12\x1b\n" +
	"\theal_type\x18\x03 \x01(\tR\bhealType\x12#\n" +
	"\rhealed_amount\x18\x04 \x01(\x05R\fhealedAmount\x12\x1f\n" +
	"\vcoins_spent\x18\x05 \x01(\x05R\n" +
	"coinsSpent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xaa\x01\n" +
	"\vHealService\x12E\n" +
	"\fPurchaseHeal\x12\x19.heal.PurchaseHealRequest\x1a\x1a.heal.PurchaseHealResponse\x12T\n" +
	"\x11GetHealingHistory\x12\x1e.heal.GetHealingHistoryRequest\x1a\x1f.heal.GetHealingHistoryResponseB\"Z network-sec-micro/api/proto/healb\x06proto3"

var (
	file_api_proto_heal_heal_proto_rawDescOnce sync.Once
	file_api_proto_heal_heal_proto_rawDescData []byte
)

func file_api_proto_heal_heal_proto_rawDescGZIP() []byte {
	file_api_proto_heal_heal_proto_rawDescOnce.Do(func() {
		file_api_proto_heal_heal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_heal_heal_proto_rawDesc), len(file_api_proto_heal_heal_proto_rawDesc)))
	})
	return file_api_proto_heal_heal_proto_rawDescData
}

var file_api_proto_heal_heal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_heal_heal_proto_goTypes = []any{
	(*PurchaseHealRequest)(nil),       // 0: heal.PurchaseHealRequest
	(*PurchaseHealResponse)(nil),      // 1: heal.PurchaseHealResponse
	(*GetHealingHistoryRequest)(nil),  // 2: heal.GetHealingHistoryRequest
	(*GetHealingHistoryResponse)(nil), // 3: heal.GetHealingHistoryResponse
	(*HealingRecord)(nil),             // 4: heal.HealingRecord
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_api_proto_heal_heal_proto_depIdxs = []int32{
	4, // 0: heal.GetHealingHistoryResponse.records:type_name -> heal.HealingRecord
	5, // 1: heal.HealingRecord.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: heal.HealService.PurchaseHeal:input_type -> heal.PurchaseHealRequest
	2, // 3: heal.HealService.GetHealingHistory:input_type -> heal.GetHealingHistoryRequest
	1, // 4: heal.HealService.PurchaseHeal:output_type -> heal.PurchaseHealResponse
	3, // 5: heal.HealService.GetHealingHistory:output_type -> heal.GetHealingHistoryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_heal_heal_proto_init() }
func file_api_proto_heal_heal_proto_init() {
	if File_api_proto_heal_heal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_heal_heal_proto_rawDesc), len(file_api_proto_heal_heal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_heal_heal_proto_goTypes,
		DependencyIndexes: file_api_proto_heal_heal_proto_depIdxs,
		MessageInfos:      file_api_proto_heal_heal_proto_msgTypes,
	}.Build()
	File_api_proto_heal_heal_proto = out.File
	file_api_proto_heal_heal_proto_goTypes = nil
	file_api_proto_heal_heal_proto_depIdxs = nil
}
