// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/heal/heal.proto

package heal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealService_PurchaseHeal_FullMethodName      = "/heal.HealService/PurchaseHeal"
	HealService_GetHealingHistory_FullMethodName = "/heal.HealService/GetHealingHistory"
)

// HealServiceClient is the client API for HealService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Heal Service
type HealServiceClient interface {
	// Purchase healing package
	PurchaseHeal(ctx context.Context, in *PurchaseHealRequest, opts ...grpc.CallOption) (*PurchaseHealResponse, error)
	// Get healing history for a warrior
	GetHealingHistory(ctx context.Context, in *GetHealingHistoryRequest, opts ...grpc.CallOption) (*GetHealingHistoryResponse, error)
}

type healServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealServiceClient(cc grpc.ClientConnInterface) HealServiceClient {
	return &healServiceClient{cc}
}

func (c *healServiceClient) PurchaseHeal(ctx context.Context, in *PurchaseHealRequest, opts ...grpc.CallOption) (*PurchaseHealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseHealResponse)
	err := c.cc.Invoke(ctx, HealService_PurchaseHeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healServiceClient) GetHealingHistory(ctx context.Context, in *GetHealingHistoryRequest, opts ...grpc.CallOption) (*GetHealingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealingHistoryResponse)
	err := c.cc.Invoke(ctx, HealService_GetHealingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealServiceServer is the server API for HealService service.
// All implementations must embed UnimplementedHealServiceServer
// for forward compatibility.
//
// Heal Service
type HealServiceServer interface {
	// Purchase healing package
	PurchaseHeal(context.Context, *PurchaseHealRequest) (*PurchaseHealResponse, error)
	// Get healing history for a warrior
	GetHealingHistory(context.Context, *GetHealingHistoryRequest) (*GetHealingHistoryResponse, error)
	mustEmbedUnimplementedHealServiceServer()
}

// UnimplementedHealServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealServiceServer struct{}

func (UnimplementedHealServiceServer) PurchaseHeal(context.Context, *PurchaseHealRequest) (*PurchaseHealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseHeal not implemented")
}
func (UnimplementedHealServiceServer) GetHealingHistory(context.Context, *GetHealingHistoryRequest) (*GetHealingHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealingHistory not implemented")
}
func (UnimplementedHealServiceServer) mustEmbedUnimplementedHealServiceServer() {}
func (UnimplementedHealServiceServer) testEmbeddedByValue()                     {}

// UnsafeHealServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealServiceServer will
// result in compilation errors.
type UnsafeHealServiceServer interface {
	mustEmbedUnimplementedHealServiceServer()
}

func RegisterHealServiceServer(s grpc.ServiceRegistrar, srv HealServiceServer) {
	// If the following call pancis, it indicates UnimplementedHealServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealService_ServiceDesc, srv)
}

func _HealService_PurchaseHeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseHealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealServiceServer).PurchaseHeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealService_PurchaseHeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealServiceServer).PurchaseHeal(ctx, req.(*PurchaseHealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealService_GetHealingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealServiceServer).GetHealingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealService_GetHealingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealServiceServer).GetHealingHistory(ctx, req.(*GetHealingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealService_ServiceDesc is the grpc.ServiceDesc for HealService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heal.HealService",
	HandlerType: (*HealServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurchaseHeal",
			Handler:    _HealService_PurchaseHeal_Handler,
		},
		{
			MethodName: "GetHealingHistory",
			Handler:    _HealService_GetHealingHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/heal/heal.proto",
}
