// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/battlespell/battlespell.proto

package battlespell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to cast a spell
type CastSpellRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BattleId            string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	SpellType           string                 `protobuf:"bytes,2,opt,name=spell_type,json=spellType,proto3" json:"spell_type,omitempty"`
	CasterUsername      string                 `protobuf:"bytes,3,opt,name=caster_username,json=casterUsername,proto3" json:"caster_username,omitempty"`
	CasterUserId        string                 `protobuf:"bytes,4,opt,name=caster_user_id,json=casterUserId,proto3" json:"caster_user_id,omitempty"`
	CasterRole          string                 `protobuf:"bytes,5,opt,name=caster_role,json=casterRole,proto3" json:"caster_role,omitempty"`
	TargetDragonId      string                 `protobuf:"bytes,6,opt,name=target_dragon_id,json=targetDragonId,proto3" json:"target_dragon_id,omitempty"`
	TargetDarkEmperorId string                 `protobuf:"bytes,7,opt,name=target_dark_emperor_id,json=targetDarkEmperorId,proto3" json:"target_dark_emperor_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CastSpellRequest) Reset() {
	*x = CastSpellRequest{}
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellRequest) ProtoMessage() {}

func (x *CastSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellRequest.ProtoReflect.Descriptor instead.
func (*CastSpellRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battlespell_battlespell_proto_rawDescGZIP(), []int{0}
}

func (x *CastSpellRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CastSpellRequest) GetSpellType() string {
	if x != nil {
		return x.SpellType
	}
	return ""
}

func (x *CastSpellRequest) GetCasterUsername() string {
	if x != nil {
		return x.CasterUsername
	}
	return ""
}

func (x *CastSpellRequest) GetCasterUserId() string {
	if x != nil {
		return x.CasterUserId
	}
	return ""
}

func (x *CastSpellRequest) GetCasterRole() string {
	if x != nil {
		return x.CasterRole
	}
	return ""
}

func (x *CastSpellRequest) GetTargetDragonId() string {
	if x != nil {
		return x.TargetDragonId
	}
	return ""
}

func (x *CastSpellRequest) GetTargetDarkEmperorId() string {
	if x != nil {
		return x.TargetDarkEmperorId
	}
	return ""
}

// Response after casting spell
type CastSpellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AffectedCount int32                  `protobuf:"varint,3,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"` // Number of participants affected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastSpellResponse) Reset() {
	*x = CastSpellResponse{}
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellResponse) ProtoMessage() {}

func (x *CastSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellResponse.ProtoReflect.Descriptor instead.
func (*CastSpellResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battlespell_battlespell_proto_rawDescGZIP(), []int{1}
}

func (x *CastSpellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CastSpellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CastSpellResponse) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

// Request to get active spells
type GetActiveSpellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSpellsRequest) Reset() {
	*x = GetActiveSpellsRequest{}
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSpellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSpellsRequest) ProtoMessage() {}

func (x *GetActiveSpellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSpellsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSpellsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battlespell_battlespell_proto_rawDescGZIP(), []int{2}
}

func (x *GetActiveSpellsRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

// Response with active spells
type GetActiveSpellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spells        []*Spell               `protobuf:"bytes,1,rep,name=spells,proto3" json:"spells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSpellsResponse) Reset() {
	*x = GetActiveSpellsResponse{}
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSpellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSpellsResponse) ProtoMessage() {}

func (x *GetActiveSpellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSpellsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveSpellsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battlespell_battlespell_proto_rawDescGZIP(), []int{3}
}

func (x *GetActiveSpellsResponse) GetSpells() []*Spell {
	if x != nil {
		return x.Spells
	}
	return nil
}

// Request to trigger wraith of dragon
type TriggerWraithOfDragonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerWraithOfDragonRequest) Reset() {
	*x = TriggerWraithOfDragonRequest{}
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWraithOfDragonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWraithOfDragonRequest) ProtoMessage() {}

func (x *TriggerWraithOfDragonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWraithOfDragonRequest.ProtoReflect.Descriptor instead.
func (*TriggerWraithOfDragonRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_battlespell_battlespell_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerWraithOfDragonRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

// Response after triggering wraith
type TriggerWraithOfDragonResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Triggered          bool                   `protobuf:"varint,1,opt,name=triggered,proto3" json:"triggered,omitempty"`
	DestroyedWarriorId string                 `protobuf:"bytes,2,opt,name=destroyed_warrior_id,json=destroyedWarriorId,proto3" json:"destroyed_warrior_id,omitempty"`
	WraithCount        int32                  `protobuf:"varint,3,opt,name=wraith_count,json=wraithCount,proto3" json:"wraith_count,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TriggerWraithOfDragonResponse) Reset() {
	*x = TriggerWraithOfDragonResponse{}
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWraithOfDragonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWraithOfDragonResponse) ProtoMessage() {}

func (x *TriggerWraithOfDragonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWraithOfDragonResponse.ProtoReflect.Descriptor instead.
func (*TriggerWraithOfDragonResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_battlespell_battlespell_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerWraithOfDragonResponse) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

func (x *TriggerWraithOfDragonResponse) GetDestroyedWarriorId() string {
	if x != nil {
		return x.DestroyedWarriorId
	}
	return ""
}

func (x *TriggerWraithOfDragonResponse) GetWraithCount() int32 {
	if x != nil {
		return x.WraithCount
	}
	return 0
}

func (x *TriggerWraithOfDragonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Spell model
type Spell struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BattleId            string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	SpellType           string                 `protobuf:"bytes,3,opt,name=spell_type,json=spellType,proto3" json:"spell_type,omitempty"`
	Side                string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	CasterUsername      string                 `protobuf:"bytes,5,opt,name=caster_username,json=casterUsername,proto3" json:"caster_username,omitempty"`
	CasterUserId        string                 `protobuf:"bytes,6,opt,name=caster_user_id,json=casterUserId,proto3" json:"caster_user_id,omitempty"`
	CasterRole          string                 `protobuf:"bytes,7,opt,name=caster_role,json=casterRole,proto3" json:"caster_role,omitempty"`
	TargetDragonId      string                 `protobuf:"bytes,8,opt,name=target_dragon_id,json=targetDragonId,proto3" json:"target_dragon_id,omitempty"`
	TargetDarkEmperorId string                 `protobuf:"bytes,9,opt,name=target_dark_emperor_id,json=targetDarkEmperorId,proto3" json:"target_dark_emperor_id,omitempty"`
	StackCount          int32                  `protobuf:"varint,10,opt,name=stack_count,json=stackCount,proto3" json:"stack_count,omitempty"`
	WraithCount         int32                  `protobuf:"varint,11,opt,name=wraith_count,json=wraithCount,proto3" json:"wraith_count,omitempty"`
	IsActive            bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CastAt              *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=cast_at,json=castAt,proto3" json:"cast_at,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Spell) Reset() {
	*x = Spell{}
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell) ProtoMessage() {}

func (x *Spell) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_battlespell_battlespell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell.ProtoReflect.Descriptor instead.
func (*Spell) Descriptor() ([]byte, []int) {
	return file_api_proto_battlespell_battlespell_proto_rawDescGZIP(), []int{6}
}

func (x *Spell) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spell) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *Spell) GetSpellType() string {
	if x != nil {
		return x.SpellType
	}
	return ""
}

func (x *Spell) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Spell) GetCasterUsername() string {
	if x != nil {
		return x.CasterUsername
	}
	return ""
}

func (x *Spell) GetCasterUserId() string {
	if x != nil {
		return x.CasterUserId
	}
	return ""
}

func (x *Spell) GetCasterRole() string {
	if x != nil {
		return x.CasterRole
	}
	return ""
}

func (x *Spell) GetTargetDragonId() string {
	if x != nil {
		return x.TargetDragonId
	}
	return ""
}

func (x *Spell) GetTargetDarkEmperorId() string {
	if x != nil {
		return x.TargetDarkEmperorId
	}
	return ""
}

func (x *Spell) GetStackCount() int32 {
	if x != nil {
		return x.StackCount
	}
	return 0
}

func (x *Spell) GetWraithCount() int32 {
	if x != nil {
		return x.WraithCount
	}
	return 0
}

func (x *Spell) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Spell) GetCastAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CastAt
	}
	return nil
}

func (x *Spell) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Spell) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_proto_battlespell_battlespell_proto protoreflect.FileDescriptor

const file_api_proto_battlespell_battlespell_proto_rawDesc = "" +
	"\n" +
	"'api/proto/battlespell/battlespell.proto\x12\vbattlespell\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\x10CastSpellRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x1d\n" +
	"\n" +
	"spell_type\x18\x02 \x01(\tR\tspellType\x12'\n" +
	"\x0fcaster_username\x18\x03 \x01(\tR\x0ecasterUsername\x12$\n" +
	"\x0ecaster_user_id\x18\x04 \x01(\tR\fcasterUserId\x12\x1f\n" +
	"\vcaster_role\x18\x05 \x01(\tR\n" +
	"casterRole\x12(\n" +
	"\x10target_dragon_id\x18\x06 \x01(\tR\x0etargetDragonId\x123\n" +
	"\x16target_dark_emperor_id\x18\a \x01(\tR\x13targetDarkEmperorId\"n\n" +
	"\x11CastSpellResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaffected_count\x18\x03 \x01(\x05R\raffectedCount\"5\n" +
	"\x16GetActiveSpellsRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"E\n" +
	"\x17GetActiveSpellsResponse\x12*\n" +
	"\x06spells\x18\x01 \x03(\v2\x12.battlespell.SpellR\x06spells\";\n" +
	"\x1cTriggerWraithOfDragonRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"\xac\x01\n" +
	"\x1dTriggerWraithOfDragonResponse\x12\x1c\n" +
	"\ttriggered\x18\x01 \x01(\bR\ttriggered\x120\n" +
	"\x14destroyed_warrior_id\x18\x02 \x01(\tR\x12destroyedWarriorId\x12!\n" +
	"\fwraith_count\x18\x03 \x01(\x05R\vwraithCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xc2\x04\n" +
	"\x05Spell\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\x12\x1d\n" +
	"\n" +
	"spell_type\x18\x03 \x01(\tR\tspellType\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12'\n" +
	"\x0fcaster_username\x18\x05 \x01(\tR\x0ecasterUsername\x12$\n" +
	"\x0ecaster_user_id\x18\x06 \x01(\tR\fcasterUserId\x12\x1f\n" +
	"\vcaster_role\x18\a \x01(\tR\n" +
	"casterRole\x12(\n" +
	"\x10target_dragon_id\x18\b \x01(\tR\x0etargetDragonId\x123\n" +
	"\x16target_dark_emperor_id\x18\t \x01(\tR\x13targetDarkEmperorId\x12\x1f\n" +
	"\vstack_count\x18\n" +
	" \x01(\x05R\n" +
	"stackCount\x12!\n" +
	"\fwraith_count\x18\v \x01(\x05R\vwraithCount\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x123\n" +
	"\acast_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x06castAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xae\x02\n" +
	"\x12BattleSpellService\x12J\n" +
	"\tCastSpell\x12\x1d.battlespell.CastSpellRequest\x1a\x1e.battlespell.CastSpellResponse\x12\\\n" +
	"\x0fGetActiveSpells\x12#.battlespell.GetActiveSpellsRequest\x1a$.battlespell.GetActiveSpellsResponse\x12n\n" +
	"\x15TriggerWraithOfDragon\x12).battlespell.TriggerWraithOfDragonRequest\x1a*.battlespell.TriggerWraithOfDragonResponseB)Z'network-sec-micro/api/proto/battlespellb\x06proto3"

var (
	file_api_proto_battlespell_battlespell_proto_rawDescOnce sync.Once
	file_api_proto_battlespell_battlespell_proto_rawDescData []byte
)

func file_api_proto_battlespell_battlespell_proto_rawDescGZIP() []byte {
	file_api_proto_battlespell_battlespell_proto_rawDescOnce.Do(func() {
		file_api_proto_battlespell_battlespell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_battlespell_battlespell_proto_rawDesc), len(file_api_proto_battlespell_battlespell_proto_rawDesc)))
	})
	return file_api_proto_battlespell_battlespell_proto_rawDescData
}

var file_api_proto_battlespell_battlespell_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_battlespell_battlespell_proto_goTypes = []any{
	(*CastSpellRequest)(nil),              // 0: battlespell.CastSpellRequest
	(*CastSpellResponse)(nil),             // 1: battlespell.CastSpellResponse
	(*GetActiveSpellsRequest)(nil),        // 2: battlespell.GetActiveSpellsRequest
	(*GetActiveSpellsResponse)(nil),       // 3: battlespell.GetActiveSpellsResponse
	(*TriggerWraithOfDragonRequest)(nil),  // 4: battlespell.TriggerWraithOfDragonRequest
	(*TriggerWraithOfDragonResponse)(nil), // 5: battlespell.TriggerWraithOfDragonResponse
	(*Spell)(nil),                         // 6: battlespell.Spell
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
}
var file_api_proto_battlespell_battlespell_proto_depIdxs = []int32{
	6, // 0: battlespell.GetActiveSpellsResponse.spells:type_name -> battlespell.Spell
	7, // 1: battlespell.Spell.cast_at:type_name -> google.protobuf.Timestamp
	7, // 2: battlespell.Spell.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: battlespell.Spell.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: battlespell.BattleSpellService.CastSpell:input_type -> battlespell.CastSpellRequest
	2, // 5: battlespell.BattleSpellService.GetActiveSpells:input_type -> battlespell.GetActiveSpellsRequest
	4, // 6: battlespell.BattleSpellService.TriggerWraithOfDragon:input_type -> battlespell.TriggerWraithOfDragonRequest
	1, // 7: battlespell.BattleSpellService.CastSpell:output_type -> battlespell.CastSpellResponse
	3, // 8: battlespell.BattleSpellService.GetActiveSpells:output_type -> battlespell.GetActiveSpellsResponse
	5, // 9: battlespell.BattleSpellService.TriggerWraithOfDragon:output_type -> battlespell.TriggerWraithOfDragonResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_battlespell_battlespell_proto_init() }
func file_api_proto_battlespell_battlespell_proto_init() {
	if File_api_proto_battlespell_battlespell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_battlespell_battlespell_proto_rawDesc), len(file_api_proto_battlespell_battlespell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_battlespell_battlespell_proto_goTypes,
		DependencyIndexes: file_api_proto_battlespell_battlespell_proto_depIdxs,
		MessageInfos:      file_api_proto_battlespell_battlespell_proto_msgTypes,
	}.Build()
	File_api_proto_battlespell_battlespell_proto = out.File
	file_api_proto_battlespell_battlespell_proto_goTypes = nil
	file_api_proto_battlespell_battlespell_proto_depIdxs = nil
}
