// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/battlespell/battlespell.proto

package battlespell

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleSpellService_CastSpell_FullMethodName             = "/battlespell.BattleSpellService/CastSpell"
	BattleSpellService_GetActiveSpells_FullMethodName       = "/battlespell.BattleSpellService/GetActiveSpells"
	BattleSpellService_TriggerWraithOfDragon_FullMethodName = "/battlespell.BattleSpellService/TriggerWraithOfDragon"
)

// BattleSpellServiceClient is the client API for BattleSpellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BattleSpell Service (gRPC methods for spell casting)
type BattleSpellServiceClient interface {
	// Cast a spell in battle
	CastSpell(ctx context.Context, in *CastSpellRequest, opts ...grpc.CallOption) (*CastSpellResponse, error)
	// Get active spells for a battle
	GetActiveSpells(ctx context.Context, in *GetActiveSpellsRequest, opts ...grpc.CallOption) (*GetActiveSpellsResponse, error)
	// Trigger Wraith of Dragon effect (called by battle service when dragon kills warrior)
	TriggerWraithOfDragon(ctx context.Context, in *TriggerWraithOfDragonRequest, opts ...grpc.CallOption) (*TriggerWraithOfDragonResponse, error)
}

type battleSpellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleSpellServiceClient(cc grpc.ClientConnInterface) BattleSpellServiceClient {
	return &battleSpellServiceClient{cc}
}

func (c *battleSpellServiceClient) CastSpell(ctx context.Context, in *CastSpellRequest, opts ...grpc.CallOption) (*CastSpellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CastSpellResponse)
	err := c.cc.Invoke(ctx, BattleSpellService_CastSpell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleSpellServiceClient) GetActiveSpells(ctx context.Context, in *GetActiveSpellsRequest, opts ...grpc.CallOption) (*GetActiveSpellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveSpellsResponse)
	err := c.cc.Invoke(ctx, BattleSpellService_GetActiveSpells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleSpellServiceClient) TriggerWraithOfDragon(ctx context.Context, in *TriggerWraithOfDragonRequest, opts ...grpc.CallOption) (*TriggerWraithOfDragonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerWraithOfDragonResponse)
	err := c.cc.Invoke(ctx, BattleSpellService_TriggerWraithOfDragon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleSpellServiceServer is the server API for BattleSpellService service.
// All implementations must embed UnimplementedBattleSpellServiceServer
// for forward compatibility.
//
// BattleSpell Service (gRPC methods for spell casting)
type BattleSpellServiceServer interface {
	// Cast a spell in battle
	CastSpell(context.Context, *CastSpellRequest) (*CastSpellResponse, error)
	// Get active spells for a battle
	GetActiveSpells(context.Context, *GetActiveSpellsRequest) (*GetActiveSpellsResponse, error)
	// Trigger Wraith of Dragon effect (called by battle service when dragon kills warrior)
	TriggerWraithOfDragon(context.Context, *TriggerWraithOfDragonRequest) (*TriggerWraithOfDragonResponse, error)
	mustEmbedUnimplementedBattleSpellServiceServer()
}

// UnimplementedBattleSpellServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleSpellServiceServer struct{}

func (UnimplementedBattleSpellServiceServer) CastSpell(context.Context, *CastSpellRequest) (*CastSpellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastSpell not implemented")
}
func (UnimplementedBattleSpellServiceServer) GetActiveSpells(context.Context, *GetActiveSpellsRequest) (*GetActiveSpellsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveSpells not implemented")
}
func (UnimplementedBattleSpellServiceServer) TriggerWraithOfDragon(context.Context, *TriggerWraithOfDragonRequest) (*TriggerWraithOfDragonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerWraithOfDragon not implemented")
}
func (UnimplementedBattleSpellServiceServer) mustEmbedUnimplementedBattleSpellServiceServer() {}
func (UnimplementedBattleSpellServiceServer) testEmbeddedByValue()                            {}

// UnsafeBattleSpellServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleSpellServiceServer will
// result in compilation errors.
type UnsafeBattleSpellServiceServer interface {
	mustEmbedUnimplementedBattleSpellServiceServer()
}

func RegisterBattleSpellServiceServer(s grpc.ServiceRegistrar, srv BattleSpellServiceServer) {
	// If the following call pancis, it indicates UnimplementedBattleSpellServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleSpellService_ServiceDesc, srv)
}

func _BattleSpellService_CastSpell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastSpellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleSpellServiceServer).CastSpell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleSpellService_CastSpell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleSpellServiceServer).CastSpell(ctx, req.(*CastSpellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleSpellService_GetActiveSpells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveSpellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleSpellServiceServer).GetActiveSpells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleSpellService_GetActiveSpells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleSpellServiceServer).GetActiveSpells(ctx, req.(*GetActiveSpellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleSpellService_TriggerWraithOfDragon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerWraithOfDragonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleSpellServiceServer).TriggerWraithOfDragon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleSpellService_TriggerWraithOfDragon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleSpellServiceServer).TriggerWraithOfDragon(ctx, req.(*TriggerWraithOfDragonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BattleSpellService_ServiceDesc is the grpc.ServiceDesc for BattleSpellService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleSpellService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battlespell.BattleSpellService",
	HandlerType: (*BattleSpellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CastSpell",
			Handler:    _BattleSpellService_CastSpell_Handler,
		},
		{
			MethodName: "GetActiveSpells",
			Handler:    _BattleSpellService_GetActiveSpells_Handler,
		},
		{
			MethodName: "TriggerWraithOfDragon",
			Handler:    _BattleSpellService_TriggerWraithOfDragon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/battlespell/battlespell.proto",
}
