// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"network-sec-micro/internal/battle"
)

// Injectors from wire.go:

func InitializeApp() (*battle.Service, *battle.Handler, error) {
	service := battle.NewService()
	handler := battle.NewHandler(service)
	return service, handler, nil
}

