apiVersion: apps/v1
kind: Deployment
metadata:
  name: enemy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enemy
  template:
    metadata:
      labels:
        app: enemy
    spec:
      containers:
        - name: enemy
          image: enemy:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: MONGODB_DATABASE
              value: enemy_db
            - name: WARRIOR_GRPC_HOST
              value: warrior:50052
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: GIN_MODE
              value: release
            - name: PORT
              value: "8083"
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: enemy
spec:
  selector:
    app: enemy
  ports:
    - port: 8083
      targetPort: 8083


