apiVersion: apps/v1
kind: Deployment
metadata:
  name: weapon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weapon
  template:
    metadata:
      labels:
        app: weapon
    spec:
      containers:
        - name: weapon
          image: weapon:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: MONGODB_DB
              value: weapon_db
            - name: PORT
              value: "8081"
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: GIN_MODE
              value: release
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: weapon
spec:
  selector:
    app: weapon
  ports:
    - port: 8081
      targetPort: 8081


